package multistate

// Tests for in-memory genesis snapshot creation and verification.
// Generated by Claude Code

import (
	"crypto/ed25519"
	"os"
	"path/filepath"
	"sync"
	"testing"
	"time"

	"github.com/lunfardo314/proxima/ledger"
	"github.com/lunfardo314/proxima/ledger/base"
	"github.com/stretchr/testify/require"
)

// testGenesisOnce ensures genesis tests only initialize the library once.
// Each test that creates genesis data should call this first.
var testGenesisOnce sync.Once

func initGenesisTestOnce() {
	testGenesisOnce.Do(func() {
		ledger.ResetForTesting()
	})
}

func TestBuildGenesisSnapshotData_Basic(t *testing.T) {
	initGenesisTestOnce()
	ledger.ResetForTesting()

	// Generate a test private key
	_, privateKey, err := ed25519.GenerateKey(nil)
	require.NoError(t, err)

	genesisTime := uint32(time.Now().Unix())

	data, err := BuildGenesisSnapshotData(privateKey, genesisTime, "test ledger")
	require.NoError(t, err)
	require.NotNil(t, data)

	// Verify identity
	require.NotNil(t, data.Identity)
	require.Equal(t, genesisTime, data.Identity.GenesisTimeUnix)
	require.Equal(t, "test ledger", data.Identity.Description)

	// Verify library YAML is set
	require.NotEmpty(t, data.LibraryYAML)

	// Verify constants are parsed
	require.NotNil(t, data.Constants)
	require.Equal(t, uint64(ledger.DefaultInitialSupply), data.Constants.InitialSupply)

	// Verify branch ID is at slot 0
	require.Equal(t, uint32(0), data.BranchID.Slot())

	// Verify root record
	require.NotNil(t, data.RootRecord.Root)
	require.Equal(t, uint64(ledger.DefaultInitialSupply), data.RootRecord.Supply)
	require.Equal(t, uint64(ledger.DefaultInitialSupply), data.RootRecord.CoverageDelta)
	require.Equal(t, uint64(ledger.DefaultInitialSupply), data.RootRecord.SlotInflation)

	// Verify store is populated
	require.NotNil(t, data.Store)
	require.Greater(t, data.Store.Len(), 0)

	// Verify bootstrap chain ID
	require.Equal(t, base.BoostrapSequencerID, data.BootstrapChainID)
}

func TestBuildGenesisSnapshotData_DefaultDescription(t *testing.T) {
	ledger.ResetForTesting()

	_, privateKey, err := ed25519.GenerateKey(nil)
	require.NoError(t, err)

	// Empty description should use default
	data, err := BuildGenesisSnapshotData(privateKey, uint32(time.Now().Unix()), "")
	require.NoError(t, err)
	require.NotEmpty(t, data.Identity.Description)
}

func TestBuildGenesisSnapshotData_InvalidPrivateKey(t *testing.T) {
	ledger.ResetForTesting()

	// Too short private key
	shortKey := make([]byte, 16)
	_, err := BuildGenesisSnapshotData(shortKey, uint32(time.Now().Unix()), "")
	require.Error(t, err)
	require.Contains(t, err.Error(), "invalid private key size")

	// Too long private key
	longKey := make([]byte, 128)
	_, err = BuildGenesisSnapshotData(longKey, uint32(time.Now().Unix()), "")
	require.Error(t, err)
}

func TestBuildGenesisSnapshotData_UpgradeLibraryStored(t *testing.T) {
	ledger.ResetForTesting()

	_, privateKey, err := ed25519.GenerateKey(nil)
	require.NoError(t, err)

	data, err := BuildGenesisSnapshotData(privateKey, uint32(time.Now().Unix()), "")
	require.NoError(t, err)

	// Verify upgrade library is stored at slot 0
	yaml, found := GetUpgradeLibraryDirect(data.Store, 0)
	require.True(t, found)
	require.Equal(t, data.LibraryYAML, yaml)

	// Verify it's the only upgrade library
	count := CountUpgradeLibraries(data.Store)
	require.Equal(t, 1, count)
}

func TestBuildGenesisSnapshotData_ThreeOutputs(t *testing.T) {
	ledger.ResetForTesting()

	_, privateKey, err := ed25519.GenerateKey(nil)
	require.NoError(t, err)

	data, err := BuildGenesisSnapshotData(privateKey, uint32(time.Now().Unix()), "")
	require.NoError(t, err)

	// Read the state
	rdr := MustNewReadable(data.Store, data.RootRecord.Root)

	// Verify all 3 UTXOs exist
	// Note: IterateUTXOIDs only counts UTXOs in the accounts partition,
	// but upgrade UTXOs are not indexed there (they don't have parseable locks).
	// So we verify each UTXO individually using HasUTXO.

	// Verify genesis output exists
	genesisOid := base.GenesisOutputID()
	require.True(t, rdr.HasUTXO(genesisOid), "genesis output should exist")

	// Verify stem output exists
	stemOid := base.GenesisStemOutputID()
	require.True(t, rdr.HasUTXO(stemOid), "stem output should exist")

	// Verify upgrade UTXO exists
	upgradeOid := base.UpgradeOutputID(0)
	require.True(t, rdr.HasUTXO(upgradeOid), "upgrade UTXO should exist")
}

func TestWriteGenesisSnapshot_RoundTrip(t *testing.T) {
	ledger.ResetForTesting()

	// Create temp directory
	tmpDir, err := os.MkdirTemp("", "genesis_snapshot_test")
	require.NoError(t, err)
	defer os.RemoveAll(tmpDir)

	// Generate test data
	_, privateKey, err := ed25519.GenerateKey(nil)
	require.NoError(t, err)

	genesisTime := uint32(time.Now().Unix())

	// Build and write snapshot
	fpath, data, err := CreateGenesisSnapshot(privateKey, genesisTime, "round trip test", tmpDir)
	require.NoError(t, err)
	require.FileExists(t, fpath)

	// Verify file name format
	require.True(t, filepath.Ext(fpath) == ".snapshot" ||
		len(filepath.Base(fpath)) > len(".snapshot"))

	// Read back the snapshot
	stream, err := OpenSnapshotFileStream(fpath)
	require.NoError(t, err)
	defer stream.Close()

	// Verify header
	require.Equal(t, snapshotFormatVersionString, stream.Header.Version)

	// Verify upgrade libraries (identity is now part of the library YAML)
	require.Len(t, stream.UpgradeLibraries, 1)
	require.Equal(t, uint32(0), stream.UpgradeLibraries[0].Slot)
	require.Equal(t, data.LibraryYAML, stream.UpgradeLibraries[0].LibraryYAML)

	// Verify branch ID
	require.Equal(t, data.BranchID, stream.BranchID)

	// Verify we can parse constants
	constants, err := stream.GetLedgerConstants()
	require.NoError(t, err)
	require.Equal(t, data.Constants.InitialSupply, constants.InitialSupply)
}

func TestVerifyGenesisSnapshot_Valid(t *testing.T) {
	ledger.ResetForTesting()

	tmpDir, err := os.MkdirTemp("", "genesis_verify_test")
	require.NoError(t, err)
	defer os.RemoveAll(tmpDir)

	_, privateKey, err := ed25519.GenerateKey(nil)
	require.NoError(t, err)

	fpath, _, err := CreateGenesisSnapshot(privateKey, uint32(time.Now().Unix()), "", tmpDir)
	require.NoError(t, err)

	// Verify should succeed
	stream, err := VerifyGenesisSnapshot(fpath)
	require.NoError(t, err)
	require.NotNil(t, stream)
	stream.Close()
}

func TestVerifyGenesisSnapshot_NonExistent(t *testing.T) {
	// This test doesn't need ResetForTesting since it doesn't create genesis data
	_, err := VerifyGenesisSnapshot("/nonexistent/path/genesis.snapshot")
	require.Error(t, err)
}

func TestGenesisSnapshotData_GetLibraryHash(t *testing.T) {
	ledger.ResetForTesting()

	_, privateKey, err := ed25519.GenerateKey(nil)
	require.NoError(t, err)

	data, err := BuildGenesisSnapshotData(privateKey, uint32(time.Now().Unix()), "")
	require.NoError(t, err)

	hash, err := data.GetLibraryHash()
	require.NoError(t, err)

	// Hash should be non-zero
	var zeroHash [32]byte
	require.NotEqual(t, zeroHash, hash)
}

func TestGenesisSnapshotData_DeterministicOutput(t *testing.T) {
	// Same private key and genesis time should produce same results
	seed := make([]byte, 32)
	for i := range seed {
		seed[i] = byte(i)
	}
	privateKey := ed25519.NewKeyFromSeed(seed)
	genesisTime := uint32(1704067200) // Fixed time

	ledger.ResetForTesting()
	data1, err := BuildGenesisSnapshotData(privateKey, genesisTime, "deterministic test")
	require.NoError(t, err)

	ledger.ResetForTesting()
	data2, err := BuildGenesisSnapshotData(privateKey, genesisTime, "deterministic test")
	require.NoError(t, err)

	// Compare key fields
	require.Equal(t, data1.Identity.GenesisTimeUnix, data2.Identity.GenesisTimeUnix)
	require.Equal(t, data1.Identity.Description, data2.Identity.Description)
	require.Equal(t, data1.BranchID, data2.BranchID)
	require.Equal(t, data1.BootstrapChainID, data2.BootstrapChainID)
	require.Equal(t, data1.RootRecord.Supply, data2.RootRecord.Supply)
	require.Equal(t, data1.LibraryYAML, data2.LibraryYAML)

	// Root commitments should be equal
	require.Equal(t, data1.RootRecord.Root.Bytes(), data2.RootRecord.Root.Bytes())
}
