package multistate

import (
	"bytes"
	"os"
	"testing"

	"github.com/lunfardo314/proxima/ledger/base"
	"github.com/lunfardo314/unitrie/common"
	"github.com/stretchr/testify/require"
)

// Tests for snapshot format with upgrade libraries.
// These tests verify that upgrade libraries are correctly written to and read from snapshots.
// Generated by Claude Code

func TestSnapshotUpgradeLibraries_Format(t *testing.T) {
	// Test the upgrade library serialization format
	// This tests the binary format: count + [slot + yaml] pairs

	// Create test data
	lib0 := []byte("library YAML for slot 0 - genesis")
	lib1000 := []byte("library YAML for slot 1000 - first upgrade")
	lib5000 := []byte("library YAML for slot 5000 - second upgrade")

	entries := []UpgradeLibraryEntry{
		{Slot: 0, LibraryYAML: lib0},
		{Slot: 1000, LibraryYAML: lib1000},
		{Slot: 5000, LibraryYAML: lib5000},
	}

	// Verify entry structure
	require.Len(t, entries, 3)
	require.Equal(t, uint32(0), entries[0].Slot)
	require.Equal(t, uint32(1000), entries[1].Slot)
	require.Equal(t, uint32(5000), entries[2].Slot)
}

func TestSnapshotUpgradeLibraries_StorageRoundTrip(t *testing.T) {
	// Test that upgrade libraries written to DB can be iterated
	store := common.NewInMemoryKVStore()

	lib0 := []byte("genesis library YAML")
	lib1000 := []byte("upgrade 1 library YAML")
	lib5000 := []byte("upgrade 2 library YAML")

	require.NoError(t, WriteUpgradeLibrary(store, 0, lib0))
	require.NoError(t, WriteUpgradeLibrary(store, 1000, lib1000))
	require.NoError(t, WriteUpgradeLibrary(store, 5000, lib5000))

	// Iterate and collect (simulates what SaveSnapshot does)
	var collected []UpgradeLibraryEntry
	IterateUpgradeLibraries(store, func(slot uint32, yaml []byte) bool {
		collected = append(collected, UpgradeLibraryEntry{Slot: slot, LibraryYAML: yaml})
		return true
	})

	require.Len(t, collected, 3)

	// Build map for order-independent verification
	libMap := make(map[uint32][]byte)
	for _, entry := range collected {
		libMap[entry.Slot] = entry.LibraryYAML
	}

	// Verify all slots are present
	require.Contains(t, libMap, uint32(0))
	require.Contains(t, libMap, uint32(1000))
	require.Contains(t, libMap, uint32(5000))

	// Verify content
	require.True(t, bytes.Equal(lib0, libMap[0]))
	require.True(t, bytes.Equal(lib1000, libMap[1000]))
	require.True(t, bytes.Equal(lib5000, libMap[5000]))
}

func TestSnapshotUpgradeLibraries_SlotSerialization(t *testing.T) {
	// Test slot byte serialization (big-endian)
	testCases := []struct {
		slot     uint32
		expected []byte
	}{
		{0, []byte{0, 0, 0, 0}},
		{1, []byte{0, 0, 0, 1}},
		{256, []byte{0, 0, 1, 0}},
		{1000, []byte{0, 0, 3, 232}},
		{5000, []byte{0, 0, 19, 136}},
		{0xFFFFFFFF, []byte{255, 255, 255, 255}},
	}

	for _, tc := range testCases {
		slotBytes := base.Slot2Bytes(tc.slot)
		require.Equal(t, tc.expected, slotBytes, "slot %d", tc.slot)

		// Verify round-trip
		recovered, err := base.SlotFromBytes(slotBytes)
		require.NoError(t, err)
		require.Equal(t, tc.slot, recovered)
	}
}

func TestSnapshotUpgradeLibraries_CountSerialization(t *testing.T) {
	// Test count serialization (little-endian)
	testCases := []struct {
		count    int
		expected []byte
	}{
		{0, []byte{0, 0, 0, 0}},
		{1, []byte{1, 0, 0, 0}},
		{3, []byte{3, 0, 0, 0}},
		{256, []byte{0, 1, 0, 0}},
		{1000, []byte{232, 3, 0, 0}},
	}

	for _, tc := range testCases {
		// Encode (same as SaveSnapshot does)
		countBytes := make([]byte, 4)
		countBytes[0] = byte(tc.count)
		countBytes[1] = byte(tc.count >> 8)
		countBytes[2] = byte(tc.count >> 16)
		countBytes[3] = byte(tc.count >> 24)
		require.Equal(t, tc.expected, countBytes, "count %d", tc.count)

		// Decode (same as OpenSnapshotFileStream does)
		decoded := int(countBytes[0]) | int(countBytes[1])<<8 | int(countBytes[2])<<16 | int(countBytes[3])<<24
		require.Equal(t, tc.count, decoded)
	}
}

func TestSnapshotUpgradeLibraries_VersionString(t *testing.T) {
	// Verify version string is correct
	require.Equal(t, "ver 1", snapshotFormatVersionString)
}

func TestSnapshotUpgradeLibraries_TmpPrefix(t *testing.T) {
	// Verify tmp prefix constant
	require.Equal(t, "__tmp__", TmpSnapshotFileNamePrefix)
}

func TestSnapshotUpgradeLibraries_EmptyStore(t *testing.T) {
	// Test behavior with empty store (no upgrades)
	store := common.NewInMemoryKVStore()

	var collected []UpgradeLibraryEntry
	IterateUpgradeLibraries(store, func(slot uint32, yaml []byte) bool {
		collected = append(collected, UpgradeLibraryEntry{Slot: slot, LibraryYAML: yaml})
		return true
	})

	require.Len(t, collected, 0)
}

func TestSnapshotUpgradeLibraries_PartitionByte(t *testing.T) {
	// Verify the upgrade library partition byte is distinct from trie partitions
	require.NotEqual(t, TriePartitionLedgerState, upgradeLibraryDBPartition)
	require.NotEqual(t, TriePartitionAccounts, upgradeLibraryDBPartition)
	require.NotEqual(t, TriePartitionChainID, upgradeLibraryDBPartition)
}

func TestSnapshotUpgradeLibraries_LargeYAML(t *testing.T) {
	// Test with large YAML content (simulates real library YAML)
	store := common.NewInMemoryKVStore()

	// Create a large YAML (100KB)
	largeYAML := bytes.Repeat([]byte("# This is a large YAML file\n"), 4000)
	require.NoError(t, WriteUpgradeLibrary(store, 0, largeYAML))

	// Verify it's stored correctly
	var collected []UpgradeLibraryEntry
	IterateUpgradeLibraries(store, func(slot uint32, yaml []byte) bool {
		collected = append(collected, UpgradeLibraryEntry{Slot: slot, LibraryYAML: yaml})
		return true
	})

	require.Len(t, collected, 1)
	require.True(t, bytes.Equal(largeYAML, collected[0].LibraryYAML))
}

func TestSnapshotUpgradeLibraries_TmpFileFilter(t *testing.T) {
	// Test that tmp files are properly identified
	tmpDir, err := os.MkdirTemp("", "snapshot_test_tmp")
	require.NoError(t, err)
	defer os.RemoveAll(tmpDir)

	// Test file name patterns
	normalFile := "00000001234567890abcdef.snapshot"
	tmpFile := TmpSnapshotFileNamePrefix + normalFile

	require.True(t, len(tmpFile) > len(normalFile))
	require.True(t, tmpFile[:len(TmpSnapshotFileNamePrefix)] == TmpSnapshotFileNamePrefix)
	require.False(t, normalFile[:len(TmpSnapshotFileNamePrefix)] == TmpSnapshotFileNamePrefix)
}
