package multistate

// This file implements upgrade UTXO injection during branch production.
// When a branch is committed, we check if any upgrade UTXOs are missing
// from the baseline state and inject them into the mutations.
//
// Generated by Claude Code

import (
	"github.com/lunfardo314/proxima/ledger"
	"github.com/lunfardo314/proxima/ledger/base"
)

// InjectMissingUpgradeUTXOs checks for any upgrade slots up to branchSlot that
// don't have their upgrade UTXO in the baseline state, and injects them into mutations.
// This ensures upgrade UTXOs are committed when crossing upgrade boundaries.
//
// Parameters:
// - muts: the mutations to inject into
// - stateReader: reader for the baseline state to check existing UTXOs
// - branchSlot: the slot of the branch being committed
//
// Returns the number of upgrade UTXOs injected.
func InjectMissingUpgradeUTXOs(muts *Mutations, stateReader IndexedStateReader, branchSlot uint32) int {
	upgradeSlots := ledger.GetAllUpgradeSlots(branchSlot)
	if len(upgradeSlots) == 0 {
		return 0
	}

	injected := 0
	for _, upgradeSlot := range upgradeSlots {
		// Generate the synthetic OutputID for this upgrade
		oid := base.UpgradeOutputID(upgradeSlot)

		// Check if it already exists in the baseline state
		if stateReader.HasUTXO(oid) {
			continue
		}

		// Get the library hash for this upgrade slot
		lib := ledger.L(upgradeSlot)
		libraryHash := lib.LibraryHash()

		// Create the upgrade UTXO
		upgradeUTXO := ledger.UpgradeUTXO(upgradeSlot, libraryHash)

		// Inject into mutations using raw clone (upgrade UTXOs don't have standard locks)
		muts.InsertAddOutputMutationRaw(upgradeUTXO.ID, upgradeUTXO.Output)
		injected++
	}

	return injected
}
