package multistate

// This file implements the storage layer for ledger library upgrades.
// Libraries are stored as full compiled YAMLs, keyed by their upgrade slot.
// The upgrade slot is the first slot where the new library version applies.
//
// Key format: upgradeLibraryDBPartition (1 byte) + slot (4 bytes big-endian)
// Value: compiled library YAML bytes
//
// Generated by Claude Code

import (
	"fmt"

	"github.com/lunfardo314/proxima/ledger/base"
	"github.com/lunfardo314/proxima/util"
	"github.com/lunfardo314/unitrie/common"
)

// MinSlotsBetweenUpgrades is the minimum number of slots required between two
// consecutive upgrades. This ensures node operators have sufficient time to
// upgrade their nodes before a new library version takes effect.
const MinSlotsBetweenUpgrades = 360

// WriteUpgradeLibrary stores a compiled library YAML for a specific upgrade slot.
// The upgrade slot is the first slot where this library version applies.
//
// Constraints enforced:
// - Upgrade slots must be strictly increasing
// - Minimum MinSlotsBetweenUpgrades slots between consecutive upgrades
// - Exception: slot 0 (genesis) can always be written if no upgrades exist
//
// Returns an error if constraints are violated.
func WriteUpgradeLibrary(store StateStore, upgradeSlot uint32, libraryYAML []byte) error {
	latestSlot, hasExisting := GetLatestUpgradeSlot(store)

	if hasExisting {
		// Slot must be strictly greater than the latest
		if upgradeSlot <= latestSlot {
			return fmt.Errorf("upgrade slot %d must be greater than latest upgrade slot %d", upgradeSlot, latestSlot)
		}
		// Enforce minimum distance between upgrades (except for genesis at slot 0)
		if latestSlot > 0 && upgradeSlot-latestSlot < MinSlotsBetweenUpgrades {
			return fmt.Errorf("upgrade slot %d is too close to previous upgrade at slot %d (minimum distance: %d slots)",
				upgradeSlot, latestSlot, MinSlotsBetweenUpgrades)
		}
	}

	key := makeUpgradeLibraryKey(upgradeSlot)
	batch := store.BatchedWriter()
	batch.Set(key, libraryYAML)
	return batch.Commit()
}

// MustWriteUpgradeLibrary is like WriteUpgradeLibrary but panics on error.
func MustWriteUpgradeLibrary(store StateStore, upgradeSlot uint32, libraryYAML []byte) {
	err := WriteUpgradeLibrary(store, upgradeSlot, libraryYAML)
	util.AssertNoError(err)
}

// GetUpgradeLibraryDirect retrieves the library YAML stored at a specific upgrade slot.
// Returns the YAML bytes and true if found, nil and false otherwise.
func GetUpgradeLibraryDirect(r common.KVReader, upgradeSlot uint32) ([]byte, bool) {
	key := makeUpgradeLibraryKey(upgradeSlot)
	data := r.Get(key)
	if len(data) == 0 {
		return nil, false
	}
	return data, true
}

// GetUpgradeLibraryForSlot finds the library version applicable to a given slot.
// It returns the library that was active at that slot (i.e., the latest upgrade
// with upgradeSlot <= slot).
// Returns: libraryYAML, upgradeSlot of that library, and whether found.
func GetUpgradeLibraryForSlot(store common.Traversable, slot uint32) (libraryYAML []byte, upgradeSlot uint32, found bool) {
	// Iterate all upgrades to find the latest one <= slot
	// Since upgrades are rare, this simple iteration is efficient enough
	IterateUpgradeLibraries(store, func(upgSlot uint32, yaml []byte) bool {
		if upgSlot <= slot {
			// This upgrade applies to the requested slot
			// Keep the latest one (highest upgrade slot <= slot)
			if !found || upgSlot > upgradeSlot {
				libraryYAML = yaml
				upgradeSlot = upgSlot
				found = true
			}
		}
		return true // continue iteration
	})
	return
}

// IterateUpgradeLibraries iterates all stored upgrade libraries in slot order (ascending).
// The callback receives the upgrade slot and the library YAML bytes.
// Return false from the callback to stop iteration.
func IterateUpgradeLibraries(store common.Traversable, fun func(upgradeSlot uint32, libraryYAML []byte) bool) {
	prefix := []byte{upgradeLibraryDBPartition}
	store.Iterator(prefix).Iterate(func(k, v []byte) bool {
		// k = partition byte + 4-byte slot
		if len(k) != 5 {
			return true // skip malformed entries
		}
		slot, err := base.SlotFromBytes(k[1:])
		util.AssertNoError(err)
		return fun(slot, v)
	})
}

// GetLatestUpgradeSlot returns the highest upgrade slot in the store.
// Returns the slot and true if any upgrades exist, 0 and false otherwise.
func GetLatestUpgradeSlot(store common.Traversable) (uint32, bool) {
	var latestSlot uint32
	found := false
	IterateUpgradeLibraries(store, func(upgradeSlot uint32, _ []byte) bool {
		if !found || upgradeSlot > latestSlot {
			latestSlot = upgradeSlot
			found = true
		}
		return true
	})
	return latestSlot, found
}

// CountUpgradeLibraries returns the number of upgrade libraries stored.
func CountUpgradeLibraries(store common.Traversable) int {
	count := 0
	IterateUpgradeLibraries(store, func(_ uint32, _ []byte) bool {
		count++
		return true
	})
	return count
}

// DeleteUpgradeLibraryForTesting removes a library at a specific upgrade slot.
// WARNING: This function is for TESTING ONLY. Upgrade libraries must never be
// deleted from the DB in production - they are required for validating historical
// transactions that were created under older library versions.
func DeleteUpgradeLibraryForTesting(store StateStore, upgradeSlot uint32) {
	key := makeUpgradeLibraryKey(upgradeSlot)
	batch := store.BatchedWriter()
	batch.Set(key, nil)
	util.AssertNoError(batch.Commit())
}

// HasUpgradeLibrary checks if a library exists at a specific upgrade slot.
func HasUpgradeLibrary(r common.KVReader, upgradeSlot uint32) bool {
	key := makeUpgradeLibraryKey(upgradeSlot)
	data := r.Get(key)
	return len(data) > 0
}

// makeUpgradeLibraryKey constructs the DB key for an upgrade library.
func makeUpgradeLibraryKey(slot uint32) []byte {
	key := make([]byte, 5)
	key[0] = upgradeLibraryDBPartition
	copy(key[1:], base.Slot2Bytes(slot))
	return key
}
