/*
Package upgrade manages pending ledger library upgrades for the Proxima network.

# Overview

The Proxima ledger uses EasyFL scripts to define transaction validation rules,
constants, and constraints. These definitions can be upgraded over time to add
new features, fix bugs, or modify parameters.

This package provides a simple mechanism for managing pending upgrades. At most
one pending upgrade can exist at any time, simplifying code organization,
testing, and the node operator experience.

# Creating a New Upgrade

To create a new upgrade, follow these steps:

1. Set the target slot in PendingUpgrade:

	var PendingUpgrade = &UpgradeDefinition{
	    Slot:             100000,  // Well in the future
	    Build:            buildUpgradeLibrary,
	    RegisterResolver: registerUpgradeResolver,
	}

2. Create pending_resolver.go with the embedded function resolver:

	func registerUpgradeResolver() {
	    ledger.RegisterResolverForUpgrade(PendingUpgrade.Slot, getResolverUpgrade1)
	}

	func getResolverUpgrade1(lib *easyfl.Library[*ledger.EvalContext]) func(string) easyfl.EmbeddedFunction[*ledger.EvalContext] {
	    return func(sym string) easyfl.EmbeddedFunction[*ledger.EvalContext] {
	        // Return embedded functions for new/modified operations
	        return nil
	    }
	}

3. Create the build function that produces the upgraded library:

	func buildUpgradeLibrary(prevYAML []byte) ([]byte, error) {
	    // Parse the previous library
	    lib, err := ledger.ParseLibraryFromYAML(prevYAML, getResolverUpgrade1)
	    if err != nil {
	        return nil, err
	    }

	    // Apply upgrades (add/replace functions)
	    err = lib.UpgradeFromYAML(upgradeDefinitionsYAML)
	    if err != nil {
	        return nil, err
	    }

	    // Return compiled YAML
	    return lib.ToYAML(true), nil
	}

4. Optionally add pending_defs.yaml with EasyFL function definitions.

# Upgrade Constraints

Upgrades can only ADD or REPLACE EasyFL functions. They cannot DELETE functions
because historical transactions must remain valid with their original rules.

When modifying an embedded function (Go code), create a new versioned
implementation and use the `embedded-as` YAML field to map to it:

	# In pending_defs.yaml
	ticksBefore:
	  embedded-as: ticksBefore_v1

Then in pending_resolver.go, return the new implementation for "ticksBefore_v1".

# Upgrade Lifecycle

1. DEVELOPMENT: Add upgrade to this package, set target slot in the future.

2. DEPLOYMENT: Node operators update their nodes. At startup, the upgrade is
   registered and stored in the DB partition. This happens BEFORE the target
   slot to ensure all nodes are ready.

3. ACTIVATION: When a branch transaction is produced at or after the target
   slot, the upgrade UTXO is injected and new rules take effect.

4. CLEANUP: After activation, PendingUpgrade can be set to nil. The upgrade
   data lives in the DB partition and embedded function code remains in the
   codebase for historical validation.

# Files in This Package

  - upgrade.go: Core types (UpgradeDefinition) and PendingUpgrade variable
  - doc.go: This documentation
  - pending.go: (user-created) Sets PendingUpgrade for current upgrade
  - pending_resolver.go: (user-created) Embedded function resolver
  - pending_defs.yaml: (optional) EasyFL definitions for the upgrade

Generated by Claude Code
*/
package upgrade
