// Package txlogger provides a queue-based async transaction logger module.
// Generated by Claude Code
package txlogger

import (
	"time"

	"github.com/lunfardo314/proxima/core/core_modules"
	"github.com/lunfardo314/proxima/global"
	"github.com/lunfardo314/proxima/ledger/base"
	"github.com/lunfardo314/proxima/txlogger"
)

type (
	environment interface {
		global.NodeGlobal
	}

	// input is the queue message structure
	input struct {
		clockTs time.Time
		msg     string
		txids   []base.TransactionID
	}

	// TxLoggerModule provides queue-based async transaction logging.
	// Implements global.TxLogWriter and global.TxLogger interfaces.
	TxLoggerModule struct {
		environment
		*core_modules.CoreModule[input]
		store *txlogger.TxLogStore
	}
)

const (
	Name = "txLogger"

	// Background task intervals
	ttlCleanupPeriod = 10 * time.Minute
	gcPeriod         = 5 * time.Minute

	// Default TTL for log records
	defaultTTL = 1 * time.Hour
)

// New creates a new TxLoggerModule.
// The store is created but not opened until TxLogEnable is called.
func New(env environment) *TxLoggerModule {
	ret := &TxLoggerModule{
		environment: env,
		store:       txlogger.New(),
	}
	ret.CoreModule = core_modules.New[input](env, Name, ret.consume)
	ret.CoreModule.Start()

	// Start background cleanup task (runs even when disabled, returns early if not enabled)
	ret.RepeatInBackground(Name+"_ttlCleanup", ttlCleanupPeriod, func() bool {
		if !ret.store.IsEnabled() {
			return true // keep running, just skip this iteration
		}
		deleted, err := ret.store.DeleteExpired(ret.getTTL())
		if err != nil {
			ret.Log().Warnf("[%s] TTL cleanup error: %v", Name, err)
		} else if deleted > 0 {
			ret.Log().Debugf("[%s] TTL cleanup deleted %d records", Name, deleted)
		}
		return true
	}, true) // skipFirst=true

	// Start Badger GC task
	ret.RepeatInBackground(Name+"_gc", gcPeriod, func() bool {
		if !ret.store.IsEnabled() {
			return true
		}
		start := time.Now()
		err := ret.store.RunGC()
		if err != nil {
			ret.Log().Debugf("[%s] GC (%v): %v", Name, time.Since(start), err)
		}
		return true
	}, true) // skipFirst=true

	return ret
}

// getTTL returns the configured TTL for log records.
// TODO: make this configurable via proxima.yaml
func (m *TxLoggerModule) getTTL() time.Duration {
	return defaultTTL
}

// consume processes queued log entries.
func (m *TxLoggerModule) consume(inp input) {
	if !m.store.IsEnabled() {
		return
	}

	// Filter transactions based on current level
	var filteredTxids []base.TransactionID
	for _, txid := range inp.txids {
		if m.store.ShouldLog(txid) {
			filteredTxids = append(filteredTxids, txid)
		}
	}

	if len(filteredTxids) == 0 {
		return
	}

	err := m.store.WriteRecord(inp.clockTs, inp.msg, filteredTxids...)

	if err != nil {
		m.Log().Warnf("[%s] write error: %v", Name, err)
	}
}

// TxLog implements global.TxLogWriter interface.
// Queues a log entry for async processing.
func (m *TxLoggerModule) TxLog(timestamp time.Time, msg string, txid ...base.TransactionID) {
	if !m.store.IsEnabled() || len(txid) == 0 {
		return
	}

	// Quick pre-filter: check if any txid would pass the level filter
	hasLoggable := false
	for _, id := range txid {
		if m.store.ShouldLog(id) {
			hasLoggable = true
			break
		}
	}
	if !hasLoggable {
		return
	}

	m.Push(input{
		clockTs: timestamp,
		msg:     msg,
		txids:   txid,
	})
}

// TxLogEnable implements global.TxLogger interface.
// Enables or disables the transaction logger with the specified level.
func (m *TxLoggerModule) TxLogEnable(lvl global.TxLogLevel) {
	if lvl == global.TxLogLevelOff {
		// Disable the logger
		if m.store.IsEnabled() {
			m.Log().Infof("[%s] disabling transaction logger", Name)
			if err := m.store.Close(); err != nil {
				m.Log().Warnf("[%s] error closing store: %v", Name, err)
			}
		}
		return
	}

	// Enable the logger
	if !m.store.IsEnabled() {
		m.Log().Infof("[%s] enabling transaction logger with level %d", Name, lvl)
		if err := m.store.Open(global.TxLogDBName); err != nil {
			m.Log().Errorf("[%s] error opening store: %v", Name, err)
			return
		}
	}
	m.store.SetLevel(lvl)
	m.Log().Infof("[%s] log level set to %d", Name, lvl)
}

// TxLogGet implements global.TxLogReader interface.
// Retrieves log records by transaction ID prefix.
// Returns records sorted by timestamp in ascending order.
func (m *TxLoggerModule) TxLogGet(txShortIDPrefix []byte, max ...int) ([]global.TxLogRecord, error) {
	return m.store.TxLogGet(txShortIDPrefix, max...)
}

// TxLogIterate implements global.TxLogReader interface.
// Iterates over log records starting from the given time.
func (m *TxLoggerModule) TxLogIterate(begin time.Time, fun func(rec global.TxLogRecord)) error {
	return m.store.TxLogIterate(begin, fun)
}

// IsEnabled returns true if the logger is currently enabled.
func (m *TxLoggerModule) IsEnabled() bool {
	return m.store.IsEnabled()
}

// Level returns the current log level.
func (m *TxLoggerModule) Level() global.TxLogLevel {
	return m.store.Level()
}

// Close closes the transaction logger store.
// Should be called during shutdown.
func (m *TxLoggerModule) Close() error {
	return m.store.Close()
}
