// Package txlogger tests
// Generated by Claude Code
package txlogger

import (
	"context"
	"os"
	"sync"
	"testing"
	"time"

	"github.com/lunfardo314/proxima/global"
	"github.com/lunfardo314/proxima/ledger/base"
	"github.com/lunfardo314/proxima/util/lines"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/stretchr/testify/require"
	"go.uber.org/zap"
)

// mockEnvironment implements the environment interface for testing
type mockEnvironment struct {
	ctx       context.Context
	cancel    context.CancelFunc
	log       *zap.SugaredLogger
	registry  *prometheus.Registry
	wg        sync.WaitGroup
	processes map[string]bool
	processMu sync.Mutex
}

func newMockEnvironment() *mockEnvironment {
	ctx, cancel := context.WithCancel(context.Background())
	logger, _ := zap.NewDevelopment()
	return &mockEnvironment{
		ctx:       ctx,
		cancel:    cancel,
		log:       logger.Sugar(),
		registry:  prometheus.NewRegistry(),
		processes: make(map[string]bool),
	}
}

func (m *mockEnvironment) Ctx() context.Context                                                     { return m.ctx }
func (m *mockEnvironment) Stop()                                                                    { m.cancel() }
func (m *mockEnvironment) IsShuttingDown() bool                                                     { return m.ctx.Err() != nil }
func (m *mockEnvironment) ClockCatchUpWithLedgerTime(ts base.LedgerTime) bool                       { return true }
func (m *mockEnvironment) Log() *zap.SugaredLogger                                                  { return m.log }
func (m *mockEnvironment) Outputs() []string                                                        { return nil }
func (m *mockEnvironment) Tracef(tag string, format string, args ...any)                            {}
func (m *mockEnvironment) TracefLog(log *zap.SugaredLogger, tag string, format string, args ...any) {}
func (m *mockEnvironment) StartTracingTags(tags ...string)                                          {}
func (m *mockEnvironment) Assertf(cond bool, format string, args ...any)                            {}
func (m *mockEnvironment) AssertNoError(err error, prefix ...string)                                {}
func (m *mockEnvironment) TopicVerbosityLevel(topic string) int                                     { return 0 }
func (m *mockEnvironment) LogTopicf(topic string, requiredLevel int, template string, args ...any)  {}
func (m *mockEnvironment) WarnTopicf(topic string, requiredLevel int, template string, args ...any) {}
func (m *mockEnvironment) IncCounter(name string)                                                   {}
func (m *mockEnvironment) DecCounter(name string)                                                   {}
func (m *mockEnvironment) SetCounter(name string, value int)                                        {}
func (m *mockEnvironment) Counter(name string) int                                                  { return 0 }
func (m *mockEnvironment) CounterLines(prefix ...string) *lines.Lines                               { return nil }
func (m *mockEnvironment) AttachmentFinished(started ...time.Time)                                  {}
func (m *mockEnvironment) TxPullParameters() (time.Duration, int)                                   { return time.Second, 3 }
func (m *mockEnvironment) DeadlockCatchingDisabled() bool                                           { return true }
func (m *mockEnvironment) LogTx(_ time.Time, _ string, _ ...base.TransactionID)                     {}
func (m *mockEnvironment) IsSnapshotting() bool                                                     { return false }
func (m *mockEnvironment) SetSnapshotting(on bool)                                                  {}
func (m *mockEnvironment) MetricsRegistry() *prometheus.Registry                                    { return m.registry }

func (m *mockEnvironment) MarkWorkProcessStarted(name string) {
	m.processMu.Lock()
	defer m.processMu.Unlock()
	m.processes[name] = true
	m.wg.Add(1)
}

func (m *mockEnvironment) MarkWorkProcessStopped(name string) {
	m.processMu.Lock()
	defer m.processMu.Unlock()
	delete(m.processes, name)
	m.wg.Done()
}

func (m *mockEnvironment) RepeatInBackground(name string, period time.Duration, fun func() bool, skipFirst ...bool) {
	skip := len(skipFirst) > 0 && skipFirst[0]
	go func() {
		if !skip {
			if !fun() {
				return
			}
		}
		ticker := time.NewTicker(period)
		defer ticker.Stop()
		for {
			select {
			case <-m.ctx.Done():
				return
			case <-ticker.C:
				if !fun() {
					return
				}
			}
		}
	}()
}

func (m *mockEnvironment) RepeatSync(period time.Duration, fun func() bool) bool {
	return true
}

func TestTxLoggerModuleBasic(t *testing.T) {
	// Create temp directory for test
	tmpDir, err := os.MkdirTemp("", "txlogger_module_test")
	require.NoError(t, err)
	defer os.RemoveAll(tmpDir)

	// Override the DB path for testing
	originalDBName := global.TxLogDBName
	// We can't easily override the constant, so we'll test with the default path
	// In a real test setup, you'd want to inject the path

	env := newMockEnvironment()
	defer env.Stop()

	// Change to temp directory so the DB is created there
	oldWd, _ := os.Getwd()
	os.Chdir(tmpDir)
	defer os.Chdir(oldWd)

	module := New(env)
	require.NotNil(t, module)
	require.False(t, module.IsEnabled())

	// Enable the logger
	module.TxLogEnable(global.TxLogLevelAllTransactions)
	require.True(t, module.IsEnabled())
	require.Equal(t, global.TxLogLevelAllTransactions, module.Level())

	// Log a transaction
	txid := base.RandomTransactionID(true, 5)
	module.TxLog(time.Now(), "test message", txid)

	// Give the queue time to process
	time.Sleep(100 * time.Millisecond)

	// Read back the record
	shortID := txid.ShortID()
	records, err := module.TxLogGet(shortID[:])
	require.NoError(t, err)
	require.Len(t, records, 1)
	require.Equal(t, "test message", records[0].Message)

	// Disable the logger
	module.TxLogEnable(global.TxLogLevelOff)
	require.False(t, module.IsEnabled())

	// Clean up - restore original path reference
	_ = originalDBName
}

func TestTxLoggerModuleLevelFiltering(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "txlogger_module_test")
	require.NoError(t, err)
	defer os.RemoveAll(tmpDir)

	env := newMockEnvironment()
	defer env.Stop()

	oldWd, _ := os.Getwd()
	os.Chdir(tmpDir)
	defer os.Chdir(oldWd)

	module := New(env)

	// Enable with branch-only level
	module.TxLogEnable(global.TxLogLevelBranchTransactionsOnly)

	// Create branch and non-branch transactions
	branchTxid := base.RandomTransactionID(true, 5, base.LedgerTime{Slot: 100, Tick: 0}) // branch
	seqTxid := base.RandomTransactionID(true, 5, base.LedgerTime{Slot: 100, Tick: 10})   // seq non-branch
	nonSeqTxid := base.RandomTransactionID(false, 5)                                     // non-sequencer

	// Log all three
	module.TxLog(time.Now(), "branch msg", branchTxid)
	module.TxLog(time.Now(), "seq msg", seqTxid)
	module.TxLog(time.Now(), "non-seq msg", nonSeqTxid)

	time.Sleep(100 * time.Millisecond)

	// Only branch should be logged
	branchShortID := branchTxid.ShortID()
	records, err := module.TxLogGet(branchShortID[:])
	require.NoError(t, err)
	require.Len(t, records, 1, "branch transaction should be logged")

	seqShortID := seqTxid.ShortID()
	records, err = module.TxLogGet(seqShortID[:])
	require.NoError(t, err)
	require.Len(t, records, 0, "non-branch sequencer transaction should not be logged")

	nonSeqShortID := nonSeqTxid.ShortID()
	records, err = module.TxLogGet(nonSeqShortID[:])
	require.NoError(t, err)
	require.Len(t, records, 0, "non-sequencer transaction should not be logged")

	module.Close()
}

func TestTxLoggerModuleBatchLog(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "txlogger_module_test")
	require.NoError(t, err)
	defer os.RemoveAll(tmpDir)

	env := newMockEnvironment()
	defer env.Stop()

	oldWd, _ := os.Getwd()
	os.Chdir(tmpDir)
	defer os.Chdir(oldWd)

	module := New(env)
	module.TxLogEnable(global.TxLogLevelAllTransactions)

	// Log multiple transactions with single call
	txids := make([]base.TransactionID, 5)
	for i := range txids {
		txids[i] = base.RandomTransactionID(false, byte(i+1))
	}

	module.TxLog(time.Now(), "batch message", txids...)

	time.Sleep(100 * time.Millisecond)

	// Verify each transaction has a record
	for _, txid := range txids {
		shortID := txid.ShortID()
		records, err := module.TxLogGet(shortID[:])
		require.NoError(t, err)
		require.Len(t, records, 1)
		require.Equal(t, "batch message", records[0].Message)
	}

	module.Close()
}
