package db_cmd

// Generated by Claude Code

import (
	"encoding/hex"

	"github.com/lunfardo314/proxima/ledger"
	"github.com/lunfardo314/proxima/ledger/base"
	"github.com/lunfardo314/proxima/ledger/multistate"
	"github.com/lunfardo314/proxima/proxi/glb"
	"github.com/spf13/cobra"
)

func initUpgradesCmd() *cobra.Command {
	upgradesCmd := &cobra.Command{
		Use:   "upgrades",
		Short: "displays full ledger upgrade history",
		Args:  cobra.NoArgs,
		Run:   runUpgradesCmd,
	}

	upgradesCmd.InitDefaultHelpCmd()
	return upgradesCmd
}

func runUpgradesCmd(_ *cobra.Command, _ []string) {
	glb.InitLedgerFromDB()
	defer glb.CloseDatabases()

	glb.Infof("Ledger Upgrade History")
	glb.Infof("======================")

	upgradeCount := multistate.CountUpgradeLibraries(glb.StateStore())
	if upgradeCount == 0 {
		glb.Infof("No upgrades found in database")
		return
	}

	glb.Infof("Total upgrades: %d\n", upgradeCount)

	// Display base library info
	baseHash := ledger.BaseLibraryHash()
	glb.Infof("Base EasyFL library (predecessor to all upgrades):")
	glb.Infof("   Hash: %s", hex.EncodeToString(baseHash[:]))
	glb.Infof("")

	// Iterate all upgrades in order
	idx := 0
	multistate.IterateUpgradeLibraries(glb.StateStore(), func(upgradeSlot uint32, libraryYAML []byte) bool {
		lib, err := ledger.ParseLibraryFromYAML(libraryYAML, ledger.GetEmbeddedFunctionResolverUpgrade0)
		if err != nil {
			glb.Infof("Upgrade %d at slot %d: ERROR parsing library: %v", idx, upgradeSlot, err)
			idx++
			return true
		}

		libHash := lib.LibraryHash()
		constants := ledger.ConstantsFromLibrary(lib)

		// Get upgrade chain data
		chainData := ledger.L(upgradeSlot).UpgradeChainData()

		glb.Infof("Upgrade %d: Slot %d", idx, upgradeSlot)
		glb.Infof("   Library hash: %s", hex.EncodeToString(libHash[:]))
		if chainData != nil {
			if chainData.PrevUpgradeSlot == base.MaxSlot {
				glb.Infof("   Previous: Base library")
			} else {
				glb.Infof("   Previous: Upgrade at slot %d", chainData.PrevUpgradeSlot)
			}
			glb.Infof("   Prev hash: %s", hex.EncodeToString(chainData.PrevLibraryHash[:]))
		}
		glb.Verbosef("   Description: %s", constants.Description)
		glb.Verbosef("   Genesis time: %d", constants.GenesisTimeUnix)
		glb.Infof("")

		idx++
		return true
	})

	// Show current active library
	glb.Infof("Current Active Library (for slot MaxSlot):")
	currentLib := ledger.L(base.MaxSlot)
	currentChainData := currentLib.UpgradeChainData()
	if currentChainData != nil {
		glb.Infof("   Upgraded at slot: %d", currentChainData.UpgradeSlot)
		glb.Infof("   Hash: %s", hex.EncodeToString(currentChainData.LibraryHash[:]))
	}
}
