// Package txlogger provides transaction event logging with dual indexing.
// Generated by Claude Code
package txlogger

import (
	"encoding/binary"
	"errors"

	"github.com/lunfardo314/proxima/ledger/base"
)

// Partition prefixes for dual indexing
const (
	partitionByTx   = 0x01
	partitionByTime = 0x02
)

// Key lengths
const (
	// keyByTxLen = 1 (partition) + 27 (TransactionIDShort) + 8 (timestamp_ns) = 36 bytes
	keyByTxLen = 1 + base.TransactionIDShortLength + 8
	// keyByTimeLen = 1 (partition) + 8 (timestamp_ns) + 27 (TransactionIDShort) = 36 bytes
	keyByTimeLen = 1 + 8 + base.TransactionIDShortLength
)

var (
	ErrInvalidKeyLength = errors.New("invalid key length")
	ErrInvalidPartition = errors.New("invalid partition prefix")
)

// makeKeyByTx creates a key for the "by transaction" index.
// Format: 0x01 || TransactionIDShort (27 bytes) || timestamp_nanosec (8 bytes)
func makeKeyByTx(txShortID base.TransactionIDShort, clockNs int64) []byte {
	key := make([]byte, keyByTxLen)
	key[0] = partitionByTx
	copy(key[1:1+base.TransactionIDShortLength], txShortID[:])
	binary.BigEndian.PutUint64(key[1+base.TransactionIDShortLength:], uint64(clockNs))
	return key
}

// makeKeyByTxPrefix creates a prefix for searching by TransactionIDShort prefix.
// Format: 0x01 || txShortIDPrefix (variable length)
func makeKeyByTxPrefix(txShortIDPrefix []byte) []byte {
	key := make([]byte, 1+len(txShortIDPrefix))
	key[0] = partitionByTx
	copy(key[1:], txShortIDPrefix)
	return key
}

// makeKeyByTime creates a key for the "by timestamp" index.
// Format: 0x02 || timestamp_nanosec (8 bytes) || TransactionIDShort (27 bytes)
func makeKeyByTime(clockNs int64, txShortID base.TransactionIDShort) []byte {
	key := make([]byte, keyByTimeLen)
	key[0] = partitionByTime
	binary.BigEndian.PutUint64(key[1:9], uint64(clockNs))
	copy(key[9:], txShortID[:])
	return key
}

// makeKeyByTimePrefix creates a prefix for the "by timestamp" partition.
// If clockNs is provided, includes the timestamp for range queries.
func makeKeyByTimePrefix(clockNs ...int64) []byte {
	if len(clockNs) == 0 {
		return []byte{partitionByTime}
	}
	key := make([]byte, 9)
	key[0] = partitionByTime
	binary.BigEndian.PutUint64(key[1:9], uint64(clockNs[0]))
	return key
}

// parseKeyByTx extracts TransactionIDShort and timestamp from a "by transaction" key.
func parseKeyByTx(key []byte) (base.TransactionIDShort, int64, error) {
	var txShortID base.TransactionIDShort
	if len(key) != keyByTxLen {
		return txShortID, 0, ErrInvalidKeyLength
	}
	if key[0] != partitionByTx {
		return txShortID, 0, ErrInvalidPartition
	}
	copy(txShortID[:], key[1:1+base.TransactionIDShortLength])
	clockNs := int64(binary.BigEndian.Uint64(key[1+base.TransactionIDShortLength:]))
	return txShortID, clockNs, nil
}

// parseKeyByTime extracts timestamp and TransactionIDShort from a "by timestamp" key.
func parseKeyByTime(key []byte) (int64, base.TransactionIDShort, error) {
	var txShortID base.TransactionIDShort
	if len(key) != keyByTimeLen {
		return 0, txShortID, ErrInvalidKeyLength
	}
	if key[0] != partitionByTime {
		return 0, txShortID, ErrInvalidPartition
	}
	clockNs := int64(binary.BigEndian.Uint64(key[1:9]))
	copy(txShortID[:], key[9:])
	return clockNs, txShortID, nil
}
