// Package txlogger provides transaction event logging with dual indexing.
// Generated by Claude Code
package txlogger

import (
	"os"
	"sort"
	"sync"
	"time"

	"github.com/dgraph-io/badger/v4"
	"github.com/lunfardo314/proxima/global"
	"github.com/lunfardo314/proxima/ledger/base"
	"github.com/lunfardo314/unitrie/adaptors/badger_adaptor"
)

// TxLogStore implements transaction event logging with dual indexing by transaction ID and timestamp.
type TxLogStore struct {
	db      *badger_adaptor.DB
	mu      sync.RWMutex
	level   global.TxLogLevel
	enabled bool
}

// New creates a new TxLogStore. The database is not opened until Enable is called.
func New() *TxLogStore {
	return &TxLogStore{
		level:   global.TxLogLevelOff,
		enabled: false,
	}
}

// Open opens (creating if needed) the database at the specified path. Called when
// enabling the logger.
//
// It returns the badger error instead of panicking (unlike MustCreateOrOpenBadgerDB):
// the txlog DB is a disposable helper, and the caller recovers from an open failure by
// wiping and recreating it rather than crashing the node — see TxLoggerModule.TxLogEnable.
func (s *TxLogStore) Open(dbPath string) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	if s.db != nil {
		return nil // already open
	}

	if err := os.MkdirAll(dbPath, 0700); err != nil {
		return err
	}
	opts := badger.DefaultOptions(dbPath)
	opts.BlockCacheSize = 32 << 20 // 32MB block cache limit
	opts.IndexCacheSize = 16 << 20 // 16MB index cache limit
	opts.Logger = nil
	bdb, err := badger.Open(opts)
	if err != nil {
		return err
	}
	s.db = badger_adaptor.New(bdb)
	s.enabled = true
	return nil
}

// Close closes the database. Called when disabling the logger.
func (s *TxLogStore) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()

	s.enabled = false
	if s.db == nil {
		return nil
	}
	err := s.db.Close()
	s.db = nil
	return err
}

// IsEnabled returns true if the logger is enabled.
func (s *TxLogStore) IsEnabled() bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.enabled
}

// Level returns the current log level.
func (s *TxLogStore) Level() global.TxLogLevel {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.level
}

// SetLevel sets the log level.
func (s *TxLogStore) SetLevel(lvl global.TxLogLevel) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.level = lvl
}

// ShouldLog returns true if the transaction should be logged based on the current level.
func (s *TxLogStore) ShouldLog(txid base.TransactionID) bool {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if !s.enabled {
		return false
	}

	switch s.level {
	case global.TxLogLevelOff:
		return false
	case global.TxLogLevelBranchTransactionsOnly:
		return txid.IsBranchTransaction()
	case global.TxLogLevelSequencerTransactionsOnly:
		return txid.IsSequencerTransaction()
	case global.TxLogLevelNonSequencerTransactionsOnly:
		return !txid.IsSequencerTransaction()
	case global.TxLogLevelAllTransactions:
		return true
	default:
		return false
	}
}

// WriteRecord writes log records to the store for one or more transactions.
// All records share the same clock timestamp and message.
// Creates entries in both the "by transaction" and "by timestamp" indexes.
//
// Holds the RLock for the full operation so that Close cannot race with an
// in-flight write and close the underlying db under our feet.
func (s *TxLogStore) WriteRecord(clockTs time.Time, msg string, txids ...base.TransactionID) error {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if !s.enabled || s.db == nil || len(txids) == 0 {
		return nil
	}

	clockNs := clockTs.UnixNano()

	batch := s.db.BatchedWriter()
	for _, txid := range txids {
		txShortID := txid.ShortID()
		keyByTx := makeKeyByTx(txShortID, clockNs)
		keyByTime := makeKeyByTime(clockNs, txShortID)
		batch.Set(keyByTx, encodeValue(txid, msg))
		batch.Set(keyByTime, []byte{0xff}) // placeholder value for time index
	}
	return batch.Commit()
}

// TxLogGet retrieves log records for transactions matching the given prefix.
// Returns records sorted by timestamp in ascending order.
// Implements global.TxLogReader interface.
//
// Holds the RLock for the full operation (see WriteRecord).
func (s *TxLogStore) TxLogGet(txShortIDPrefix []byte, max ...int) ([]global.TxLogRecord, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if !s.enabled || s.db == nil {
		return nil, ErrLoggerDisabled
	}

	maxRecords := 100 // default limit
	if len(max) > 0 && max[0] > 0 {
		maxRecords = max[0]
	}

	prefix := makeKeyByTxPrefix(txShortIDPrefix)
	var records []global.TxLogRecord

	s.db.Iterator(prefix).Iterate(func(k, v []byte) bool {
		txShortID, clockNs, err := parseKeyByTx(k)
		if err != nil {
			return true // skip invalid keys
		}

		txid, msg := decodeValue(v, txShortID)

		records = append(records, global.TxLogRecord{
			ID:             txid,
			ClockTimestamp: time.Unix(0, clockNs),
			Message:        msg,
		})
		return true
	})

	// Sort by timestamp ascending
	sort.Slice(records, func(i, j int) bool {
		return records[i].ClockTimestamp.Before(records[j].ClockTimestamp)
	})

	// Apply max limit after sorting
	if len(records) > maxRecords {
		records = records[:maxRecords]
	}

	return records, nil
}

// TxLogIterate iterates over log records starting from the given time.
// Implements global.TxLogReader interface.
//
// Holds the RLock for the full operation (see WriteRecord).
func (s *TxLogStore) TxLogIterate(begin time.Time, fun func(rec global.TxLogRecord)) error {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if !s.enabled || s.db == nil {
		return ErrLoggerDisabled
	}

	beginNs := begin.UnixNano()
	// TODO: optimize by using a smarter prefix strategy for range queries
	// For now, iterate all time-indexed records and filter
	prefix := makeKeyByTimePrefix()

	s.db.Iterator(prefix).Iterate(func(k, v []byte) bool {
		clockNs, txShortID, err := parseKeyByTime(k)
		if err != nil {
			return true // skip invalid keys
		}

		// Skip records before the exact begin time
		if clockNs < beginNs {
			return true
		}

		// Look up the value from the "by transaction" index (contains ledger timestamp + message)
		keyByTx := makeKeyByTx(txShortID, clockNs)
		val := s.db.Get(keyByTx)

		txid, msg := decodeValue(val, txShortID)

		fun(global.TxLogRecord{
			ID:             txid,
			ClockTimestamp: time.Unix(0, clockNs),
			Message:        msg,
		})
		return true
	})

	return nil
}

// ttlBatchSize is the maximum number of keys accumulated in memory before a
// deletion batch is committed. Two keys per record (time index + tx index), so
// 10_000 keys = 5_000 records per commit. Keeps peak memory during cleanup
// bounded to a few MB regardless of backlog size and stays well under Badger's
// MaxTxnSize, which otherwise fails the whole commit with "Txn is too big to
// fit into one request" when the backlog is large.
const ttlBatchSize = 10_000

// DeleteExpired deletes records older than the specified TTL.
// Returns the number of deleted records.
//
// Streams the deletion in bounded batches (see ttlBatchSize) so peak memory is
// independent of backlog size. The previous implementation collected the entire
// expired set into one []byte slice and committed a single batch, which (1)
// allocated proportionally to the backlog — observed spikes up to ~3 GB on
// acc nodes with ~500 MB of accumulated txlog — and (2) failed atomically with
// Badger's "Txn is too big" error once the batch exceeded MaxTxnSize, leaving
// the backlog intact for the next 10-minute cycle.
//
// Holds the RLock for the full operation (see WriteRecord). This is the
// path that triggered the shutdown-time SIGSEGV when Close ran concurrently
// with an in-flight iteration.
func (s *TxLogStore) DeleteExpired(ttl time.Duration) (int, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if !s.enabled || s.db == nil {
		return 0, nil
	}

	cutoffNs := time.Now().Add(-ttl).UnixNano()
	prefix := makeKeyByTimePrefix()

	keysToDelete := make([][]byte, 0, ttlBatchSize)
	totalDeleted := 0
	var flushErr error

	flush := func() error {
		if len(keysToDelete) == 0 {
			return nil
		}
		batch := s.db.BatchedWriter()
		for _, key := range keysToDelete {
			batch.Set(key, nil) // nil value deletes the key
		}
		if err := batch.Commit(); err != nil {
			return err
		}
		totalDeleted += len(keysToDelete) / 2 // each record contributes 2 keys
		keysToDelete = keysToDelete[:0]
		return nil
	}

	s.db.Iterator(prefix).Iterate(func(k, v []byte) bool {
		clockNs, txShortID, err := parseKeyByTime(k)
		if err != nil {
			return true
		}
		if clockNs >= cutoffNs {
			// records are sorted by time; past the cutoff means the rest are all live
			return false
		}
		keysToDelete = append(keysToDelete, copyBytes(k))
		keysToDelete = append(keysToDelete, makeKeyByTx(txShortID, clockNs))
		if len(keysToDelete) >= ttlBatchSize {
			if err := flush(); err != nil {
				flushErr = err
				return false // stop iteration on commit failure
			}
		}
		return true
	})

	if flushErr != nil {
		return totalDeleted, flushErr
	}
	if err := flush(); err != nil {
		return totalDeleted, err
	}
	return totalDeleted, nil
}

// RunGC runs Badger's garbage collection.
//
// Holds the RLock for the full operation (see WriteRecord).
func (s *TxLogStore) RunGC() error {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if !s.enabled || s.db == nil {
		return nil
	}

	return s.db.RunValueLogGC(0.5)
}

// copyBytes creates a copy of a byte slice.
func copyBytes(b []byte) []byte {
	if b == nil {
		return nil
	}
	c := make([]byte, len(b))
	copy(c, b)
	return c
}

// ErrLoggerDisabled is returned when trying to read from a disabled logger.
var ErrLoggerDisabled = newError("txlogger is disabled") // placeholder, should define proper error

type txLogError struct {
	msg string
}

func (e *txLogError) Error() string {
	return e.msg
}

func newError(msg string) error {
	return &txLogError{msg: msg}
}
