// Package txlogger provides transaction event logging with dual indexing.
// Generated by Claude Code
package txlogger

import (
	"bytes"
	"sync"
	"time"

	"github.com/dgraph-io/badger/v4"
	"github.com/lunfardo314/proxima/global"
	"github.com/lunfardo314/proxima/ledger/base"
	"github.com/lunfardo314/unitrie/adaptors/badger_adaptor"
)

// TxLogStore implements transaction event logging with dual indexing by transaction ID and timestamp.
type TxLogStore struct {
	db      *badger_adaptor.DB
	mu      sync.RWMutex
	level   global.TxLogLevel
	enabled bool
}

// New creates a new TxLogStore. The database is not opened until Enable is called.
func New() *TxLogStore {
	return &TxLogStore{
		level:   global.TxLogLevelOff,
		enabled: false,
	}
}

// Open opens the database at the specified path. Called when enabling the logger.
func (s *TxLogStore) Open(dbPath string) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	if s.db != nil {
		return nil // already open
	}

	opts := badger.DefaultOptions(dbPath)
	opts.BlockCacheSize = 32 << 20 // 32MB block cache limit
	opts.IndexCacheSize = 16 << 20 // 16MB index cache limit

	bdb := badger_adaptor.MustCreateOrOpenBadgerDB(dbPath, opts)
	s.db = badger_adaptor.New(bdb)
	s.enabled = true
	return nil
}

// Close closes the database. Called when disabling the logger.
func (s *TxLogStore) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()

	s.enabled = false
	if s.db == nil {
		return nil
	}
	err := s.db.Close()
	s.db = nil
	return err
}

// IsEnabled returns true if the logger is enabled.
func (s *TxLogStore) IsEnabled() bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.enabled
}

// Level returns the current log level.
func (s *TxLogStore) Level() global.TxLogLevel {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.level
}

// SetLevel sets the log level.
func (s *TxLogStore) SetLevel(lvl global.TxLogLevel) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.level = lvl
}

// ShouldLog returns true if the transaction should be logged based on the current level.
func (s *TxLogStore) ShouldLog(txid base.TransactionID) bool {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if !s.enabled {
		return false
	}

	switch s.level {
	case global.TxLogLevelOff:
		return false
	case global.TxLogLevelBranchTransactionsOnly:
		return txid.IsBranchTransaction()
	case global.TxLogLevelSequencerTransactionsOnly:
		return txid.IsSequencerTransaction()
	case global.TxLogLevelNonSequencerTransactionsOnly:
		return !txid.IsSequencerTransaction()
	case global.TxLogLevelAllTransactionsOnly:
		return true
	default:
		return false
	}
}

// WriteRecord writes a single log record to the store.
// Creates entries in both the "by transaction" and "by timestamp" indexes.
func (s *TxLogStore) WriteRecord(clockTs time.Time, msg string, txid base.TransactionID) error {
	s.mu.RLock()
	db := s.db
	enabled := s.enabled
	s.mu.RUnlock()

	if !enabled || db == nil {
		return nil
	}

	clockNs := clockTs.UnixNano()
	txShortID := txid.ShortID()

	// Create keys for both indexes
	keyByTx := makeKeyByTx(txShortID, clockNs)
	keyByTime := makeKeyByTime(clockNs, txShortID)

	// Write both entries in a batch
	batch := db.BatchedWriter()
	batch.Set(keyByTx, []byte(msg))
	batch.Set(keyByTime, []byte{0xff}) // placeholder value for time index
	return batch.Commit()
}

// WriteRecordBatch writes the same log message for multiple transactions.
// All records share the same clock timestamp and message.
func (s *TxLogStore) WriteRecordBatch(clockTs time.Time, msg string, txids []base.TransactionID) error {
	s.mu.RLock()
	db := s.db
	enabled := s.enabled
	s.mu.RUnlock()

	if !enabled || db == nil || len(txids) == 0 {
		return nil
	}

	clockNs := clockTs.UnixNano()
	msgBytes := []byte(msg)

	batch := db.BatchedWriter()
	for _, txid := range txids {
		txShortID := txid.ShortID()
		keyByTx := makeKeyByTx(txShortID, clockNs)
		keyByTime := makeKeyByTime(clockNs, txShortID)
		batch.Set(keyByTx, msgBytes)
		batch.Set(keyByTime, []byte{0xff})
	}
	return batch.Commit()
}

// TxLogGet retrieves log records for transactions matching the given prefix.
// Implements global.TxLogReader interface.
func (s *TxLogStore) TxLogGet(txShortIDPrefix []byte, max ...int) ([]global.TxLogRecord, error) {
	s.mu.RLock()
	db := s.db
	enabled := s.enabled
	s.mu.RUnlock()

	if !enabled || db == nil {
		return nil, ErrLoggerDisabled
	}

	maxRecords := 100 // default limit
	if len(max) > 0 && max[0] > 0 {
		maxRecords = max[0]
	}

	prefix := makeKeyByTxPrefix(txShortIDPrefix)
	var records []global.TxLogRecord

	db.Iterator(prefix).Iterate(func(k, v []byte) bool {
		if len(records) >= maxRecords {
			return false
		}

		txShortID, clockNs, err := parseKeyByTx(k)
		if err != nil {
			return true // skip invalid keys
		}

		// Reconstruct TransactionID (partial - only ShortID portion is available)
		// Note: The full TransactionID cannot be reconstructed without the 5-byte timestamp prefix
		// For display purposes, we create a TransactionID with zero timestamp
		var txid base.TransactionID
		copy(txid[base.LedgerTimeByteLength:], txShortID[:])

		records = append(records, global.TxLogRecord{
			ID:             txid,
			ClockTimestamp: time.Unix(0, clockNs),
			Message:        string(v),
		})
		return true
	})

	return records, nil
}

// TxLogIterate iterates over log records starting from the given time.
// Implements global.TxLogReader interface.
func (s *TxLogStore) TxLogIterate(begin time.Time, fun func(rec global.TxLogRecord)) error {
	s.mu.RLock()
	db := s.db
	enabled := s.enabled
	s.mu.RUnlock()

	if !enabled || db == nil {
		return ErrLoggerDisabled
	}

	beginNs := begin.UnixNano()
	// TODO: optimize by using a smarter prefix strategy for range queries
	// For now, iterate all time-indexed records and filter
	prefix := makeKeyByTimePrefix()

	db.Iterator(prefix).Iterate(func(k, v []byte) bool {
		clockNs, txShortID, err := parseKeyByTime(k)
		if err != nil {
			return true // skip invalid keys
		}

		// Skip records before the exact begin time
		if clockNs < beginNs {
			return true
		}

		// Reconstruct partial TransactionID
		var txid base.TransactionID
		copy(txid[base.LedgerTimeByteLength:], txShortID[:])

		// Look up the message from the "by transaction" index
		keyByTx := makeKeyByTx(txShortID, clockNs)
		msg := db.Get(keyByTx)

		fun(global.TxLogRecord{
			ID:             txid,
			ClockTimestamp: time.Unix(0, clockNs),
			Message:        string(msg),
		})
		return true
	})

	return nil
}

// DeleteExpired deletes records older than the specified TTL.
// Returns the number of deleted records.
func (s *TxLogStore) DeleteExpired(ttl time.Duration) (int, error) {
	s.mu.RLock()
	db := s.db
	enabled := s.enabled
	s.mu.RUnlock()

	if !enabled || db == nil {
		return 0, nil
	}

	cutoffNs := time.Now().Add(-ttl).UnixNano()
	prefix := makeKeyByTimePrefix()

	// Collect keys to delete
	var keysToDelete [][]byte

	db.Iterator(prefix).Iterate(func(k, v []byte) bool {
		clockNs, txShortID, err := parseKeyByTime(k)
		if err != nil {
			return true
		}

		if clockNs < cutoffNs {
			// Add both keys to delete list
			keysToDelete = append(keysToDelete, copyBytes(k))
			keysToDelete = append(keysToDelete, makeKeyByTx(txShortID, clockNs))
		} else {
			// Records are sorted by time, so we can stop when we reach non-expired records
			return false
		}
		return true
	})

	if len(keysToDelete) == 0 {
		return 0, nil
	}

	// Delete in batch
	batch := db.BatchedWriter()
	for _, key := range keysToDelete {
		batch.Set(key, nil) // nil value deletes the key
	}
	err := batch.Commit()
	if err != nil {
		return 0, err
	}

	return len(keysToDelete) / 2, nil // each record has 2 keys
}

// RunGC runs Badger's garbage collection.
func (s *TxLogStore) RunGC() error {
	s.mu.RLock()
	db := s.db
	enabled := s.enabled
	s.mu.RUnlock()

	if !enabled || db == nil {
		return nil
	}

	return db.RunValueLogGC(0.5)
}

// copyBytes creates a copy of a byte slice.
func copyBytes(b []byte) []byte {
	if b == nil {
		return nil
	}
	c := make([]byte, len(b))
	copy(c, b)
	return c
}

// ErrLoggerDisabled is returned when trying to read from a disabled logger.
var ErrLoggerDisabled = bytes.ErrTooLarge // placeholder, should define proper error

func init() {
	ErrLoggerDisabled = newError("txlogger is disabled")
}

type txLogError struct {
	msg string
}

func (e *txLogError) Error() string {
	return e.msg
}

func newError(msg string) error {
	return &txLogError{msg: msg}
}
