// Package txlogger provides transaction event logging with dual indexing.
// Generated by Claude Code
package txlogger

import (
	"sort"
	"sync"
	"time"

	"github.com/dgraph-io/badger/v4"
	"github.com/lunfardo314/proxima/global"
	"github.com/lunfardo314/proxima/ledger/base"
	"github.com/lunfardo314/unitrie/adaptors/badger_adaptor"
)

// TxLogStore implements transaction event logging with dual indexing by transaction ID and timestamp.
type TxLogStore struct {
	db      *badger_adaptor.DB
	mu      sync.RWMutex
	level   global.TxLogLevel
	enabled bool
}

// New creates a new TxLogStore. The database is not opened until Enable is called.
func New() *TxLogStore {
	return &TxLogStore{
		level:   global.TxLogLevelOff,
		enabled: false,
	}
}

// Open opens the database at the specified path. Called when enabling the logger.
func (s *TxLogStore) Open(dbPath string) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	if s.db != nil {
		return nil // already open
	}

	opts := badger.DefaultOptions(dbPath)
	opts.BlockCacheSize = 32 << 20 // 32MB block cache limit
	opts.IndexCacheSize = 16 << 20 // 16MB index cache limit

	bdb := badger_adaptor.MustCreateOrOpenBadgerDB(dbPath, opts)
	s.db = badger_adaptor.New(bdb)
	s.enabled = true
	return nil
}

// Close closes the database. Called when disabling the logger.
func (s *TxLogStore) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()

	s.enabled = false
	if s.db == nil {
		return nil
	}
	err := s.db.Close()
	s.db = nil
	return err
}

// IsEnabled returns true if the logger is enabled.
func (s *TxLogStore) IsEnabled() bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.enabled
}

// Level returns the current log level.
func (s *TxLogStore) Level() global.TxLogLevel {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.level
}

// SetLevel sets the log level.
func (s *TxLogStore) SetLevel(lvl global.TxLogLevel) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.level = lvl
}

// ShouldLog returns true if the transaction should be logged based on the current level.
func (s *TxLogStore) ShouldLog(txid base.TransactionID) bool {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if !s.enabled {
		return false
	}

	switch s.level {
	case global.TxLogLevelOff:
		return false
	case global.TxLogLevelBranchTransactionsOnly:
		return txid.IsBranchTransaction()
	case global.TxLogLevelSequencerTransactionsOnly:
		return txid.IsSequencerTransaction()
	case global.TxLogLevelNonSequencerTransactionsOnly:
		return !txid.IsSequencerTransaction()
	case global.TxLogLevelAllTransactions:
		return true
	default:
		return false
	}
}

// WriteRecord writes log records to the store for one or more transactions.
// All records share the same clock timestamp and message.
// Creates entries in both the "by transaction" and "by timestamp" indexes.
//
// Holds the RLock for the full operation so that Close cannot race with an
// in-flight write and close the underlying db under our feet.
func (s *TxLogStore) WriteRecord(clockTs time.Time, msg string, txids ...base.TransactionID) error {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if !s.enabled || s.db == nil || len(txids) == 0 {
		return nil
	}

	clockNs := clockTs.UnixNano()

	batch := s.db.BatchedWriter()
	for _, txid := range txids {
		txShortID := txid.ShortID()
		keyByTx := makeKeyByTx(txShortID, clockNs)
		keyByTime := makeKeyByTime(clockNs, txShortID)
		batch.Set(keyByTx, encodeValue(txid, msg))
		batch.Set(keyByTime, []byte{0xff}) // placeholder value for time index
	}
	return batch.Commit()
}

// TxLogGet retrieves log records for transactions matching the given prefix.
// Returns records sorted by timestamp in ascending order.
// Implements global.TxLogReader interface.
//
// Holds the RLock for the full operation (see WriteRecord).
func (s *TxLogStore) TxLogGet(txShortIDPrefix []byte, max ...int) ([]global.TxLogRecord, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if !s.enabled || s.db == nil {
		return nil, ErrLoggerDisabled
	}

	maxRecords := 100 // default limit
	if len(max) > 0 && max[0] > 0 {
		maxRecords = max[0]
	}

	prefix := makeKeyByTxPrefix(txShortIDPrefix)
	var records []global.TxLogRecord

	s.db.Iterator(prefix).Iterate(func(k, v []byte) bool {
		txShortID, clockNs, err := parseKeyByTx(k)
		if err != nil {
			return true // skip invalid keys
		}

		txid, msg := decodeValue(v, txShortID)

		records = append(records, global.TxLogRecord{
			ID:             txid,
			ClockTimestamp: time.Unix(0, clockNs),
			Message:        msg,
		})
		return true
	})

	// Sort by timestamp ascending
	sort.Slice(records, func(i, j int) bool {
		return records[i].ClockTimestamp.Before(records[j].ClockTimestamp)
	})

	// Apply max limit after sorting
	if len(records) > maxRecords {
		records = records[:maxRecords]
	}

	return records, nil
}

// TxLogIterate iterates over log records starting from the given time.
// Implements global.TxLogReader interface.
//
// Holds the RLock for the full operation (see WriteRecord).
func (s *TxLogStore) TxLogIterate(begin time.Time, fun func(rec global.TxLogRecord)) error {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if !s.enabled || s.db == nil {
		return ErrLoggerDisabled
	}

	beginNs := begin.UnixNano()
	// TODO: optimize by using a smarter prefix strategy for range queries
	// For now, iterate all time-indexed records and filter
	prefix := makeKeyByTimePrefix()

	s.db.Iterator(prefix).Iterate(func(k, v []byte) bool {
		clockNs, txShortID, err := parseKeyByTime(k)
		if err != nil {
			return true // skip invalid keys
		}

		// Skip records before the exact begin time
		if clockNs < beginNs {
			return true
		}

		// Look up the value from the "by transaction" index (contains ledger timestamp + message)
		keyByTx := makeKeyByTx(txShortID, clockNs)
		val := s.db.Get(keyByTx)

		txid, msg := decodeValue(val, txShortID)

		fun(global.TxLogRecord{
			ID:             txid,
			ClockTimestamp: time.Unix(0, clockNs),
			Message:        msg,
		})
		return true
	})

	return nil
}

// DeleteExpired deletes records older than the specified TTL.
// Returns the number of deleted records.
//
// Holds the RLock for the full operation (see WriteRecord). This is the
// path that triggered the shutdown-time SIGSEGV when Close ran concurrently
// with an in-flight iteration.
func (s *TxLogStore) DeleteExpired(ttl time.Duration) (int, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if !s.enabled || s.db == nil {
		return 0, nil
	}

	cutoffNs := time.Now().Add(-ttl).UnixNano()
	prefix := makeKeyByTimePrefix()

	// Collect keys to delete
	var keysToDelete [][]byte

	s.db.Iterator(prefix).Iterate(func(k, v []byte) bool {
		clockNs, txShortID, err := parseKeyByTime(k)
		if err != nil {
			return true
		}

		if clockNs < cutoffNs {
			// Add both keys to delete list
			keysToDelete = append(keysToDelete, copyBytes(k))
			keysToDelete = append(keysToDelete, makeKeyByTx(txShortID, clockNs))
		} else {
			// Records are sorted by time, so we can stop when we reach non-expired records
			return false
		}
		return true
	})

	if len(keysToDelete) == 0 {
		return 0, nil
	}

	// Delete in batch
	batch := s.db.BatchedWriter()
	for _, key := range keysToDelete {
		batch.Set(key, nil) // nil value deletes the key
	}
	err := batch.Commit()
	if err != nil {
		return 0, err
	}

	return len(keysToDelete) / 2, nil // each record has 2 keys
}

// RunGC runs Badger's garbage collection.
//
// Holds the RLock for the full operation (see WriteRecord).
func (s *TxLogStore) RunGC() error {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if !s.enabled || s.db == nil {
		return nil
	}

	return s.db.RunValueLogGC(0.5)
}

// copyBytes creates a copy of a byte slice.
func copyBytes(b []byte) []byte {
	if b == nil {
		return nil
	}
	c := make([]byte, len(b))
	copy(c, b)
	return c
}

// ErrLoggerDisabled is returned when trying to read from a disabled logger.
var ErrLoggerDisabled = newError("txlogger is disabled") // placeholder, should define proper error

type txLogError struct {
	msg string
}

func (e *txLogError) Error() string {
	return e.msg
}

func newError(msg string) error {
	return &txLogError{msg: msg}
}
