// Package txlogger tests
// Generated by Claude Code
package txlogger

import (
	"os"
	"testing"
	"time"

	"github.com/lunfardo314/proxima/global"
	"github.com/lunfardo314/proxima/ledger/base"
	"github.com/stretchr/testify/require"
)

func TestKeyEncoding(t *testing.T) {
	// Test key encoding and decoding for "by transaction" keys
	t.Run("key_by_tx", func(t *testing.T) {
		var txShortID base.TransactionIDShort
		for i := range txShortID {
			txShortID[i] = byte(i)
		}
		clockNs := int64(1234567890123456789)

		key := makeKeyByTx(txShortID, clockNs)
		require.Equal(t, keyByTxLen, len(key), "key length should be %d", keyByTxLen)
		require.Equal(t, byte(partitionByTx), key[0], "first byte should be partition prefix")

		parsedShortID, parsedClockNs, err := parseKeyByTx(key)
		require.NoError(t, err)
		require.Equal(t, txShortID, parsedShortID)
		require.Equal(t, clockNs, parsedClockNs)
	})

	// Test key encoding and decoding for "by timestamp" keys
	t.Run("key_by_time", func(t *testing.T) {
		var txShortID base.TransactionIDShort
		for i := range txShortID {
			txShortID[i] = byte(i + 100)
		}
		clockNs := int64(1709876543210987654)

		key := makeKeyByTime(clockNs, txShortID)
		require.Equal(t, keyByTimeLen, len(key), "key length should be %d", keyByTimeLen)
		require.Equal(t, byte(partitionByTime), key[0], "first byte should be partition prefix")

		parsedClockNs, parsedShortID, err := parseKeyByTime(key)
		require.NoError(t, err)
		require.Equal(t, txShortID, parsedShortID)
		require.Equal(t, clockNs, parsedClockNs)
	})

	// Test prefix creation for "by transaction" searches
	t.Run("key_by_tx_prefix", func(t *testing.T) {
		prefix := []byte{0x01, 0x02, 0x03, 0x04}
		key := makeKeyByTxPrefix(prefix)
		require.Equal(t, 5, len(key)) // 1 partition + 4 prefix bytes
		require.Equal(t, byte(partitionByTx), key[0])
		require.Equal(t, prefix, key[1:])
	})

	// Test prefix creation for "by timestamp" searches
	t.Run("key_by_time_prefix", func(t *testing.T) {
		// Without timestamp
		prefix := makeKeyByTimePrefix()
		require.Equal(t, 1, len(prefix))
		require.Equal(t, byte(partitionByTime), prefix[0])

		// With timestamp
		clockNs := int64(1234567890)
		prefixWithTime := makeKeyByTimePrefix(clockNs)
		require.Equal(t, 9, len(prefixWithTime)) // 1 partition + 8 timestamp
		require.Equal(t, byte(partitionByTime), prefixWithTime[0])
	})
}

func TestStoreBasicOperations(t *testing.T) {
	// Create a temporary directory for the test database
	tmpDir, err := os.MkdirTemp("", "txlogger_test")
	require.NoError(t, err)
	defer os.RemoveAll(tmpDir)

	dbPath := tmpDir + "/test.txlog"

	store := New()
	require.False(t, store.IsEnabled())

	// Open the store
	err = store.Open(dbPath)
	require.NoError(t, err)
	require.True(t, store.IsEnabled())

	// Set level to log all transactions
	store.SetLevel(global.TxLogLevelAllTransactionsOnly)
	require.Equal(t, global.TxLogLevelAllTransactionsOnly, store.Level())

	// Create a test transaction ID
	txid := base.RandomTransactionID(true, 5)
	clockTs := time.Now()
	msg := "test message"

	// Write a record
	err = store.WriteRecord(clockTs, msg, txid)
	require.NoError(t, err)

	// Read back the record using the full TransactionIDShort
	shortID := txid.ShortID()
	records, err := store.TxLogGet(shortID[:])
	require.NoError(t, err)
	require.Len(t, records, 1)
	require.Equal(t, msg, records[0].Message)

	// Close the store
	err = store.Close()
	require.NoError(t, err)
	require.False(t, store.IsEnabled())
}

func TestStorePrefixSearch(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "txlogger_test")
	require.NoError(t, err)
	defer os.RemoveAll(tmpDir)

	dbPath := tmpDir + "/test.txlog"

	store := New()
	err = store.Open(dbPath)
	require.NoError(t, err)
	defer store.Close()

	store.SetLevel(global.TxLogLevelAllTransactionsOnly)

	// Create multiple transaction IDs with similar prefixes
	// by manually setting the first few bytes
	var txids []base.TransactionID
	for i := 0; i < 5; i++ {
		txid := base.RandomTransactionID(false, byte(i+1))
		// Set first 4 bytes of ShortID to create common prefix
		shortID := txid.ShortID()
		shortID[0] = 0xAA
		shortID[1] = 0xBB
		shortID[2] = 0xCC
		shortID[3] = byte(i) // different last byte

		// Reconstruct txid with modified short ID
		txid = base.NewTransactionID(txid.Timestamp(), shortID, txid.IsSequencerTransaction())
		txids = append(txids, txid)

		err = store.WriteRecord(time.Now().Add(time.Duration(i)*time.Millisecond), "msg"+string(rune('0'+i)), txid)
		require.NoError(t, err)
	}

	// Search with 3-byte prefix (should match all 5)
	records, err := store.TxLogGet([]byte{0xAA, 0xBB, 0xCC})
	require.NoError(t, err)
	require.Len(t, records, 5, "should find all 5 transactions with common prefix")

	// Search with 4-byte prefix (should match only one)
	records, err = store.TxLogGet([]byte{0xAA, 0xBB, 0xCC, 0x02})
	require.NoError(t, err)
	require.Len(t, records, 1, "should find only one transaction with specific prefix")
	require.Equal(t, "msg2", records[0].Message)

	// Search with max limit
	records, err = store.TxLogGet([]byte{0xAA, 0xBB, 0xCC}, 3)
	require.NoError(t, err)
	require.Len(t, records, 3, "should return max 3 records")
}

func TestStoreBatchWrite(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "txlogger_test")
	require.NoError(t, err)
	defer os.RemoveAll(tmpDir)

	dbPath := tmpDir + "/test.txlog"

	store := New()
	err = store.Open(dbPath)
	require.NoError(t, err)
	defer store.Close()

	store.SetLevel(global.TxLogLevelAllTransactionsOnly)

	// Create multiple transaction IDs
	var txids []base.TransactionID
	for i := 0; i < 10; i++ {
		txids = append(txids, base.RandomTransactionID(i%2 == 0, byte(i+1)))
	}

	// Write batch
	clockTs := time.Now()
	msg := "batch message"
	err = store.WriteRecordBatch(clockTs, msg, txids)
	require.NoError(t, err)

	// Verify each transaction has a record
	for _, txid := range txids {
		shortID := txid.ShortID()
		records, err := store.TxLogGet(shortID[:])
		require.NoError(t, err)
		require.Len(t, records, 1, "each transaction should have one record")
		require.Equal(t, msg, records[0].Message)
	}
}

func TestStoreTimeIteration(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "txlogger_test")
	require.NoError(t, err)
	defer os.RemoveAll(tmpDir)

	dbPath := tmpDir + "/test.txlog"

	store := New()
	err = store.Open(dbPath)
	require.NoError(t, err)
	defer store.Close()

	store.SetLevel(global.TxLogLevelAllTransactionsOnly)

	// Write records with different timestamps
	baseTime := time.Now()
	for i := 0; i < 10; i++ {
		txid := base.RandomTransactionID(false, byte(i+1))
		ts := baseTime.Add(time.Duration(i) * time.Second)
		err = store.WriteRecord(ts, "msg"+string(rune('0'+i)), txid)
		require.NoError(t, err)
	}

	// Iterate from middle
	midTime := baseTime.Add(5 * time.Second)
	var collected []global.TxLogRecord
	err = store.TxLogIterate(midTime, func(rec global.TxLogRecord) {
		collected = append(collected, rec)
	})
	require.NoError(t, err)
	require.GreaterOrEqual(t, len(collected), 5, "should find records from midpoint onward")
}

func TestStoreTTLCleanup(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "txlogger_test")
	require.NoError(t, err)
	defer os.RemoveAll(tmpDir)

	dbPath := tmpDir + "/test.txlog"

	store := New()
	err = store.Open(dbPath)
	require.NoError(t, err)
	defer store.Close()

	store.SetLevel(global.TxLogLevelAllTransactionsOnly)

	// Write an "old" record by using a past timestamp
	oldTime := time.Now().Add(-2 * time.Hour)
	oldTxid := base.RandomTransactionID(false, 1)
	err = store.WriteRecord(oldTime, "old message", oldTxid)
	require.NoError(t, err)

	// Write a "new" record
	newTime := time.Now()
	newTxid := base.RandomTransactionID(false, 2)
	err = store.WriteRecord(newTime, "new message", newTxid)
	require.NoError(t, err)

	// Verify both records exist
	oldShortID := oldTxid.ShortID()
	records, err := store.TxLogGet(oldShortID[:])
	require.NoError(t, err)
	require.Len(t, records, 1)

	newShortID := newTxid.ShortID()
	records, err = store.TxLogGet(newShortID[:])
	require.NoError(t, err)
	require.Len(t, records, 1)

	// Delete records older than 1 hour
	deleted, err := store.DeleteExpired(1 * time.Hour)
	require.NoError(t, err)
	require.Equal(t, 1, deleted, "should delete 1 old record")

	// Verify old record is gone
	records, err = store.TxLogGet(oldShortID[:])
	require.NoError(t, err)
	require.Len(t, records, 0, "old record should be deleted")

	// Verify new record still exists
	records, err = store.TxLogGet(newShortID[:])
	require.NoError(t, err)
	require.Len(t, records, 1, "new record should still exist")
}

func TestShouldLog(t *testing.T) {
	store := New()

	// When disabled, should never log
	require.False(t, store.ShouldLog(base.RandomTransactionID(true, 1)))

	// Simulate enabled state (without actually opening a DB)
	store.enabled = true

	// Test different levels
	branchTxid := base.RandomTransactionID(true, 1, base.LedgerTime{Slot: 100, Tick: 0}) // branch: seq + tick=0
	seqTxid := base.RandomTransactionID(true, 1, base.LedgerTime{Slot: 100, Tick: 10})   // sequencer: seq + tick>0
	nonSeqTxid := base.RandomTransactionID(false, 1)                                      // non-sequencer

	store.SetLevel(global.TxLogLevelOff)
	require.False(t, store.ShouldLog(branchTxid))
	require.False(t, store.ShouldLog(seqTxid))
	require.False(t, store.ShouldLog(nonSeqTxid))

	store.SetLevel(global.TxLogLevelBranchTransactionsOnly)
	require.True(t, store.ShouldLog(branchTxid))
	require.False(t, store.ShouldLog(seqTxid))
	require.False(t, store.ShouldLog(nonSeqTxid))

	store.SetLevel(global.TxLogLevelSequencerTransactionsOnly)
	require.True(t, store.ShouldLog(branchTxid)) // branch is also sequencer
	require.True(t, store.ShouldLog(seqTxid))
	require.False(t, store.ShouldLog(nonSeqTxid))

	store.SetLevel(global.TxLogLevelNonSequencerTransactionsOnly)
	require.False(t, store.ShouldLog(branchTxid))
	require.False(t, store.ShouldLog(seqTxid))
	require.True(t, store.ShouldLog(nonSeqTxid))

	store.SetLevel(global.TxLogLevelAllTransactionsOnly)
	require.True(t, store.ShouldLog(branchTxid))
	require.True(t, store.ShouldLog(seqTxid))
	require.True(t, store.ShouldLog(nonSeqTxid))
}

func TestDisabledLoggerReturnsError(t *testing.T) {
	store := New()

	// Reading from disabled logger should return error
	_, err := store.TxLogGet([]byte{0x01, 0x02})
	require.Error(t, err)
	require.Equal(t, ErrLoggerDisabled, err)

	err = store.TxLogIterate(time.Now(), func(rec global.TxLogRecord) {})
	require.Error(t, err)
	require.Equal(t, ErrLoggerDisabled, err)

	// Writing to disabled logger should be a no-op (no error)
	err = store.WriteRecord(time.Now(), "test", base.RandomTransactionID(false, 1))
	require.NoError(t, err)
}
