package ledger

import (
	"crypto/ed25519"
	"sort"
	"sync"
	"sync/atomic"
	"time"

	"github.com/lunfardo314/easyfl"
	"github.com/lunfardo314/proxima/ledger/base"
	"github.com/lunfardo314/proxima/util"
	"github.com/lunfardo314/unitrie/common"
)

// LibraryCache holds cached library versions keyed by their upgrade slot.
// Libraries are lazily loaded from the DB partition on first access.
// Since upgrades are rare, no cache eviction is needed - node restart resets the cache.
//
// Generated by Claude Code
type LibraryCache struct {
	mu       sync.RWMutex
	store    common.Traversable    // DB store for loading library YAMLs
	cache    map[uint32]*Library   // upgrade slot -> parsed library
	resolvers map[uint32]ResolverFactory // upgrade slot -> resolver factory
}

// ResolverFactory creates an embedded function resolver for a library.
// Each upgrade version has its own resolver factory.
type ResolverFactory func(lib *easyfl.Library[*EvalContext]) func(string) easyfl.EmbeddedFunction[*EvalContext]

var (
	libraryCache       *LibraryCache
	libraryCacheMutex  sync.RWMutex
	// ledgerReset is set to true when ResetForTesting is called.
	// Background goroutines can check this to avoid accessing nil Const.
	ledgerReset atomic.Bool

	// nextPendingUpgradeSlot tracks the next upgrade slot that might need UTXO injection.
	// This is an optimization to avoid scanning all upgrades on every branch commit.
	// Value meanings:
	// - 0: not initialized (will scan all upgrades)
	// - MaxSlot: no pending upgrades (all upgrade UTXOs are in state)
	// - other: the next upgrade slot that might need injection
	nextPendingUpgradeSlot atomic.Uint32
)

// RegisterResolverForUpgrade registers an embedded function resolver factory for a specific upgrade slot.
// This must be called during initialization, before any library access.
// Each upgrade (0, 1, 2, ...) should register its resolver here.
func RegisterResolverForUpgrade(upgradeSlot uint32, factory ResolverFactory) {
	libraryCacheMutex.Lock()
	defer libraryCacheMutex.Unlock()

	if libraryCache == nil {
		libraryCache = &LibraryCache{
			cache:     make(map[uint32]*Library),
			resolvers: make(map[uint32]ResolverFactory),
		}
	}
	libraryCache.resolvers[upgradeSlot] = factory
}

// L returns the library version applicable to the given slot.
// For the latest library version, use L(base.MaxSlot).
// Libraries are lazily loaded from DB and cached on first access.
func L(slot uint32) *Library {
	libraryCacheMutex.RLock()
	defer libraryCacheMutex.RUnlock()

	util.Assertf(libraryCache != nil, "ledger library cache not initialized")
	util.Assertf(libraryCache.store != nil, "ledger library cache store not set")

	return libraryCache.getOrLoad(slot)
}

// getOrLoad retrieves a library from cache or loads it from DB.
// Caller must hold at least a read lock on libraryCacheMutex.
func (lc *LibraryCache) getOrLoad(slot uint32) *Library {
	// Find the applicable upgrade slot for this slot
	upgradeSlot, yamlData := lc.findLibraryForSlot(slot)

	lc.mu.RLock()
	if lib, ok := lc.cache[upgradeSlot]; ok {
		lc.mu.RUnlock()
		return lib
	}
	lc.mu.RUnlock()

	// Not in cache, need to load and parse
	lc.mu.Lock()
	defer lc.mu.Unlock()

	// Double-check after acquiring write lock
	if lib, ok := lc.cache[upgradeSlot]; ok {
		return lib
	}

	// Parse the library with the appropriate resolver
	lib := lc.parseLibrary(upgradeSlot, yamlData)
	lc.cache[upgradeSlot] = lib
	return lib
}

// findLibraryForSlot finds the library YAML applicable to the given slot.
// Returns the upgrade slot and YAML data.
func (lc *LibraryCache) findLibraryForSlot(slot uint32) (uint32, []byte) {
	// Import the multistate package functions via interface to avoid circular imports
	// We use the store directly which implements common.Traversable

	// Iterate all upgrades to find the latest one <= slot
	var foundSlot uint32
	var foundYAML []byte
	found := false

	prefix := []byte{upgradeLibraryDBPartition}
	lc.store.Iterator(prefix).Iterate(func(k, v []byte) bool {
		if len(k) != 5 {
			return true // skip malformed entries
		}
		upgSlot, err := base.SlotFromBytes(k[1:])
		util.AssertNoError(err)

		if upgSlot <= slot {
			if !found || upgSlot > foundSlot {
				foundSlot = upgSlot
				foundYAML = v
				found = true
			}
		}
		return true
	})

	util.Assertf(found, "no library found for slot %d", slot)
	return foundSlot, foundYAML
}

// upgradeLibraryDBPartition is the DB partition byte for upgrade libraries.
// This must match the constant in multistate/roots.go.
// Value: PartitionOther(2) + 1 + 1 + 1 + 1 = 6
const upgradeLibraryDBPartition = 0x06

// parseLibrary parses a library YAML using the resolver for the given upgrade slot.
func (lc *LibraryCache) parseLibrary(upgradeSlot uint32, yamlData []byte) *Library {
	resolver, ok := lc.resolvers[upgradeSlot]
	util.Assertf(ok, "no resolver registered for upgrade slot %d", upgradeSlot)

	lib, err := ParseLibraryFromYAML(yamlData, resolver)
	util.AssertNoError(err)

	result := newLibrary(lib, yamlData)
	result.registerConstraints()
	return result
}

// MustInitLibraryCache initializes the library cache with a state store.
// The store is used for lazy loading of library YAMLs from the upgrade DB partition.
// This must be called after RegisterResolverForUpgrade for all known upgrades.
func MustInitLibraryCache(store common.Traversable) {
	var lib *Library

	// Scope for the lock - release before running inline tests to avoid deadlock
	// (inline tests call L() which needs to acquire the read lock)
	func() {
		libraryCacheMutex.Lock()
		defer libraryCacheMutex.Unlock()

		util.Assertf(libraryCache != nil, "must register resolvers before initializing cache")
		util.Assertf(libraryCache.store == nil, "library cache already initialized")

		libraryCache.store = store
		libraryCache.cache = make(map[uint32]*Library)

		ledgerReset.Store(false)

		// Pre-load the genesis library (slot 0) to initialize constants
		lib = libraryCache.getOrLoad(0)
		initConstantsSingleton(lib.Library)
	}()

	// Run inline tests after releasing the lock to avoid deadlock
	lib.runInlineTests()
}

// MustInitSingleton initializes the ledger with identity data bytes.
// DEPRECATED: Use MustInitLibraryCache with a state store instead.
// This function is kept for backward compatibility during migration.
func MustInitSingleton(identityData []byte) {
	libraryCacheMutex.Lock()

	// Create a minimal cache with the provided data
	if libraryCache == nil {
		libraryCache = &LibraryCache{
			cache:     make(map[uint32]*Library),
			resolvers: make(map[uint32]ResolverFactory),
		}
	}
	libraryCache.resolvers[0] = GetEmbeddedFunctionResolverUpgrade0

	lib, err := ParseLibraryFromYAML(identityData, GetEmbeddedFunctionResolverUpgrade0)
	util.AssertNoError(err)

	result := newLibrary(lib, identityData)
	result.registerConstraints()
	libraryCache.cache[0] = result

	// Set a dummy store that always returns the genesis library
	libraryCache.store = &singleLibraryStore{data: identityData}

	libraryCacheMutex.Unlock()

	initConstantsSingleton(result.Library)

	ledgerReset.Store(false)

	result.runInlineTests()
}

// singleLibraryStore is a minimal store implementation for backward compatibility.
// It only supports a single library at slot 0.
type singleLibraryStore struct {
	data []byte
}

func (s *singleLibraryStore) Iterator(prefix []byte) common.KVIterator {
	return &singleLibraryIterator{data: s.data, done: false}
}

type singleLibraryIterator struct {
	data []byte
	done bool
}

func (it *singleLibraryIterator) Iterate(fun func(k, v []byte) bool) {
	if it.done {
		return
	}
	it.done = true
	// Key: partition byte (0x07) + slot 0 (4 bytes)
	key := []byte{upgradeLibraryDBPartition, 0, 0, 0, 0}
	fun(key, it.data)
}

func (it *singleLibraryIterator) IterateKeys(fun func(k []byte) bool) {
	if it.done {
		return
	}
	it.done = true
	key := []byte{upgradeLibraryDBPartition, 0, 0, 0, 0}
	fun(key)
}

// GetAllUpgradeSlots returns all upgrade slots up to and including maxSlot.
// The slots are returned in ascending order.
func GetAllUpgradeSlots(maxSlot uint32) []uint32 {
	libraryCacheMutex.RLock()
	defer libraryCacheMutex.RUnlock()

	if libraryCache == nil || libraryCache.store == nil {
		return nil
	}

	var slots []uint32
	prefix := []byte{upgradeLibraryDBPartition}
	libraryCache.store.Iterator(prefix).Iterate(func(k, v []byte) bool {
		if len(k) != 5 {
			return true // skip malformed entries
		}
		slot, err := base.SlotFromBytes(k[1:])
		util.AssertNoError(err)

		if slot <= maxSlot {
			slots = append(slots, slot)
		}
		return true
	})

	sort.Slice(slots, func(i, j int) bool {
		return slots[i] < slots[j]
	})

	return slots
}

// HasPendingUpgradeForSlot checks if there might be a pending upgrade that needs
// injection at or before the given slot. This is an optimization to avoid
// scanning all upgrades on every branch commit.
//
// Returns true if:
// - nextPendingUpgradeSlot is 0 (not initialized, need to check)
// - branchSlot >= nextPendingUpgradeSlot (might have pending upgrades)
func HasPendingUpgradeForSlot(branchSlot uint32) bool {
	pending := nextPendingUpgradeSlot.Load()
	if pending == 0 {
		// Not initialized, need to check all upgrades
		return true
	}
	return branchSlot >= pending
}

// UpdateNextPendingUpgradeSlot updates the tracking after upgrade UTXOs have been
// injected up to and including afterSlot. Sets the next pending slot to the first
// upgrade slot > afterSlot, or MaxSlot if none exists.
func UpdateNextPendingUpgradeSlot(afterSlot uint32) {
	allSlots := GetAllUpgradeSlots(base.MaxSlot)
	for _, slot := range allSlots {
		if slot > afterSlot {
			nextPendingUpgradeSlot.Store(slot)
			return
		}
	}
	// No more pending upgrades
	nextPendingUpgradeSlot.Store(base.MaxSlot)
}

// InitNextPendingUpgradeSlot initializes the pending upgrade tracking at startup.
// It checks which upgrade UTXOs are missing from the state and sets the next
// pending slot accordingly.
//
// This function should be called after MustInitLibraryCache and with access to
// the latest state reader.
func InitNextPendingUpgradeSlot(hasUTXO func(base.OutputID) bool) {
	allSlots := GetAllUpgradeSlots(base.MaxSlot)
	for _, slot := range allSlots {
		oid := base.UpgradeOutputID(slot)
		if !hasUTXO(oid) {
			// Found the first missing upgrade UTXO
			nextPendingUpgradeSlot.Store(slot)
			return
		}
	}
	// All upgrade UTXOs exist in state
	nextPendingUpgradeSlot.Store(base.MaxSlot)
}

// ResetForTesting clears the ledger singleton to allow re-initialization.
// This is only for testing purposes to get fresh genesis timestamps per test.
// DO NOT use in production code.
func ResetForTesting() {
	ledgerReset.Store(true)
	libraryCacheMutex.Lock()
	defer libraryCacheMutex.Unlock()
	libraryCache = nil
	Const = nil
	nextPendingUpgradeSlot.Store(0)
}

// IsReset returns true if the ledger has been reset via ResetForTesting.
// Background goroutines can check this to avoid accessing nil Const during shutdown.
func IsReset() bool {
	return ledgerReset.Load()
}

// InitWithTestingLedgerIDData for testing

type ParametersOption func(par *InitParameters)

func InitWithTestingLedgerIDData(opts ...ParametersOption) ed25519.PrivateKey {
	params, pk := GetTestingLedgerParams(31415926535)
	for _, opt := range opts {
		opt(&params)
	}
	lib := LibraryFromParameters(params)
	MustInitSingleton(lib.ToYAML(true))
	return pk
}

func WithTickDuration(duration time.Duration) ParametersOption {
	return func(par *InitParameters) {
		par.TickDuration = duration
	}
}

func WithTransactionPace(transactionPace int) ParametersOption {
	return func(par *InitParameters) {
		par.TransactionPaceTicks = transactionPace
	}
}

func WithTransactionPaceSequencer(transactionPace int) ParametersOption {
	return func(par *InitParameters) {
		par.TransactionPaceSequencerTicks = transactionPace
	}
}
