package ledger

// This file defines the upgrade commitment UTXO format.
// Upgrade UTXOs commit to library upgrades at specific slots.
//
// UTXO Format:
// - Amount: 0 (no tokens)
// - Lock: empty inline data (unspendable - evaluates to false)
// - Third constraint: inline data containing the library hash (32 bytes)
//
// The synthetic OutputID is created using base.UpgradeOutputID(upgradeSlot).
//
// Generated by Claude Code

import (
	"fmt"

	"github.com/lunfardo314/easyfl"
	"github.com/lunfardo314/proxima/ledger/base"
)

// UpgradeUTXO creates an upgrade commitment UTXO.
// This is an unspendable output that commits to a library hash at a specific upgrade slot.
//
// Parameters:
// - upgradeSlot: the slot number for this upgrade
// - libraryHash: 32-byte hash of the compiled library YAML
//
// Returns:
// - OutputWithID containing the upgrade commitment UTXO
func UpgradeUTXO(upgradeSlot uint32, libraryHash [32]byte) *OutputWithID {
	output := NewOutput(func(o *OutputBuilder) {
		// Amount: 0 (no tokens)
		o.WithAmounts(0)

		// Lock: empty inline data (evaluates to false, making output unspendable)
		o.PutConstraint(easyfl.InlineDataBytecode(nil), ConstraintIndexLock)

		// Third constraint: library hash as inline data
		hashData := easyfl.InlineDataBytecode(libraryHash[:])
		o.MustPushConstraint(hashData)
	})

	return &OutputWithID{
		ID:     base.UpgradeOutputID(upgradeSlot),
		Output: output,
	}
}

// ParseUpgradeUTXO parses an output and verifies it's a valid upgrade UTXO.
// Returns the library hash if valid, error otherwise.
func ParseUpgradeUTXO(o *Output) ([32]byte, error) {
	var hash [32]byte

	// Check amount is 0
	if o.TokenBalance() != 0 {
		return hash, fmt.Errorf("upgrade UTXO must have 0 token balance, got %d", o.TokenBalance())
	}

	// Check we have at least 3 constraints
	if o.NumConstraints() < 3 {
		return hash, fmt.Errorf("upgrade UTXO must have at least 3 constraints, got %d", o.NumConstraints())
	}

	// Get the hash from the third constraint (index 2)
	hashData, err := o.ConstraintAt(2)
	if err != nil {
		return hash, fmt.Errorf("failed to get hash constraint: %w", err)
	}

	// Strip inline data prefix
	rawHash := easyfl.StripDataPrefix(hashData)
	if len(rawHash) != 32 {
		return hash, fmt.Errorf("upgrade UTXO hash must be 32 bytes, got %d", len(rawHash))
	}

	copy(hash[:], rawHash)
	return hash, nil
}

// IsUpgradeUTXO checks if an output with ID is a valid upgrade UTXO.
func IsUpgradeUTXO(o *OutputWithID) bool {
	// Check if the OutputID is a synthetic upgrade OutputID
	if !base.IsUpgradeOutputID(o.ID) {
		return false
	}

	// Try to parse as upgrade UTXO
	_, err := ParseUpgradeUTXO(o.Output)
	return err == nil
}

// VerifyUpgradeUTXO verifies that an upgrade UTXO matches the expected library hash.
func VerifyUpgradeUTXO(o *OutputWithID, expectedHash [32]byte) error {
	if !base.IsUpgradeOutputID(o.ID) {
		return fmt.Errorf("not a valid upgrade OutputID")
	}

	hash, err := ParseUpgradeUTXO(o.Output)
	if err != nil {
		return err
	}

	if hash != expectedHash {
		return fmt.Errorf("library hash mismatch")
	}

	return nil
}
