// Transaction logger API handlers
// Generated by Claude Code
package server

import (
	"encoding/hex"
	"encoding/json"
	"net/http"
	"strconv"
	"time"

	"github.com/lunfardo314/proxima/api"
	"github.com/lunfardo314/proxima/global"
)

const defaultMaxTxLogRecords = 100

// txLogEnable handles POST /api/v1/txlog/enable?level=<level>
// Enables or disables the transaction logger with the specified level.
func (srv *server) txLogEnable(w http.ResponseWriter, r *http.Request) {
	api.SetHeader(w)
	srv.Tracef(TraceTag, "txLogEnable invoked")

	if r.Method != http.MethodPost {
		api.WriteErr(w, "method not allowed, use POST")
		return
	}

	if !srv.TxLogOnOffAPIEnabled() {
		api.WriteErr(w, "txlog on/off API is disabled by node configuration")
		return
	}

	levelStr := r.URL.Query().Get("level")
	level := parseTxLogLevelString(levelStr)

	srv.TxLogEnable(level)

	resp := api.TxLogEnableResponse{
		Enabled: srv.TxLogIsEnabled(),
		Level:   txLogLevelToString(srv.TxLogLevel()),
	}

	respBytes, err := json.Marshal(&resp)
	if err != nil {
		api.WriteErr(w, "failed to marshal response")
		return
	}
	if _, err = w.Write(respBytes); err != nil {
		srv.Log().Warnf("txLogEnable: failed to write response: %v", err)
	}
}

// txLogGet handles GET /api/v1/txlog/get?prefix=<hex_prefix>&max=<max>
// Retrieves log records by transaction ID short prefix.
func (srv *server) txLogGet(w http.ResponseWriter, r *http.Request) {
	api.SetHeader(w)
	srv.Tracef(TraceTag, "txLogGet invoked")

	if !srv.TxLogIsEnabled() {
		api.WriteErr(w, "transaction logger is disabled")
		return
	}

	// Parse prefix parameter (required)
	prefixHex := r.URL.Query().Get("prefix")
	if prefixHex == "" {
		api.WriteErr(w, "missing required parameter: prefix")
		return
	}

	prefix, err := hex.DecodeString(prefixHex)
	if err != nil {
		api.WriteErr(w, "invalid prefix: must be hex-encoded")
		return
	}

	// Parse optional max parameter
	maxRecords := defaultMaxTxLogRecords
	if maxStr := r.URL.Query().Get("max"); maxStr != "" {
		maxRecords, err = strconv.Atoi(maxStr)
		if err != nil || maxRecords <= 0 {
			api.WriteErr(w, "invalid max parameter: must be positive integer")
			return
		}
	}

	// Get records from the logger
	records, err := srv.TxLogGet(prefix, maxRecords)
	if err != nil {
		api.WriteErr(w, err.Error())
		return
	}

	// Convert to API response format
	resp := api.TxLogResponse{
		Records: make([]api.TxLogRecord, len(records)),
	}
	for i, rec := range records {
		resp.Records[i] = api.TxLogRecord{
			TxIDShort:      hex.EncodeToString(rec.ID[5:]), // Skip 5-byte timestamp prefix
			ClockTimestamp: rec.ClockTimestamp.UnixNano(),
			Message:        rec.Message,
		}
	}

	respBytes, err := json.Marshal(&resp)
	if err != nil {
		api.WriteErr(w, "failed to marshal response")
		return
	}
	if _, err = w.Write(respBytes); err != nil {
		srv.Log().Warnf("txLogGet: failed to write response: %v", err)
	}
}

// txLogRange handles GET /api/v1/txlog/range?from=<unix_ns>&to=<unix_ns>&max=<max>
// Retrieves log records within a time range.
func (srv *server) txLogRange(w http.ResponseWriter, r *http.Request) {
	api.SetHeader(w)
	srv.Tracef(TraceTag, "txLogRange invoked")

	if !srv.TxLogIsEnabled() {
		api.WriteErr(w, "transaction logger is disabled")
		return
	}

	// Parse from parameter (required)
	fromStr := r.URL.Query().Get("from")
	if fromStr == "" {
		api.WriteErr(w, "missing required parameter: from")
		return
	}
	fromNs, err := strconv.ParseInt(fromStr, 10, 64)
	if err != nil {
		api.WriteErr(w, "invalid from parameter: must be Unix nanoseconds")
		return
	}
	fromTime := time.Unix(0, fromNs)

	// Parse optional to parameter (defaults to now)
	toTime := time.Now()
	if toStr := r.URL.Query().Get("to"); toStr != "" {
		toNs, err := strconv.ParseInt(toStr, 10, 64)
		if err != nil {
			api.WriteErr(w, "invalid to parameter: must be Unix nanoseconds")
			return
		}
		toTime = time.Unix(0, toNs)
	}

	// Parse optional max parameter
	maxRecords := defaultMaxTxLogRecords
	if maxStr := r.URL.Query().Get("max"); maxStr != "" {
		maxRecords, err = strconv.Atoi(maxStr)
		if err != nil || maxRecords <= 0 {
			api.WriteErr(w, "invalid max parameter: must be positive integer")
			return
		}
	}

	// Collect records within the time range
	var records []api.TxLogRecord
	err = srv.TxLogIterate(fromTime, func(rec global.TxLogRecord) {
		if len(records) >= maxRecords {
			return
		}
		if rec.ClockTimestamp.After(toTime) {
			return
		}
		records = append(records, api.TxLogRecord{
			TxIDShort:      hex.EncodeToString(rec.ID[5:]), // Skip 5-byte timestamp prefix
			ClockTimestamp: rec.ClockTimestamp.UnixNano(),
			Message:        rec.Message,
		})
	})
	if err != nil {
		api.WriteErr(w, err.Error())
		return
	}

	resp := api.TxLogResponse{
		Records: records,
	}

	respBytes, err := json.Marshal(&resp)
	if err != nil {
		api.WriteErr(w, "failed to marshal response")
		return
	}
	if _, err = w.Write(respBytes); err != nil {
		srv.Log().Warnf("txLogRange: failed to write response: %v", err)
	}
}

// parseTxLogLevelString converts a string level name to TxLogLevel.
func parseTxLogLevelString(s string) global.TxLogLevel {
	switch s {
	case "off", "":
		return global.TxLogLevelOff
	case "branch":
		return global.TxLogLevelBranchTransactionsOnly
	case "sequencer":
		return global.TxLogLevelSequencerTransactionsOnly
	case "non_sequencer":
		return global.TxLogLevelNonSequencerTransactionsOnly
	case "all":
		return global.TxLogLevelAllTransactions
	default:
		return global.TxLogLevelOff
	}
}

// txLogLevelToString converts a TxLogLevel to its string name.
func txLogLevelToString(level global.TxLogLevel) string {
	switch level {
	case global.TxLogLevelOff:
		return "off"
	case global.TxLogLevelBranchTransactionsOnly:
		return "branch"
	case global.TxLogLevelSequencerTransactionsOnly:
		return "sequencer"
	case global.TxLogLevelNonSequencerTransactionsOnly:
		return "non_sequencer"
	case global.TxLogLevelAllTransactions:
		return "all"
	default:
		return "unknown"
	}
}
