// Transaction logger CLI commands
// Generated by Claude Code
package node_cmd

import (
	"sort"
	"time"

	"github.com/lunfardo314/proxima/api"
	"github.com/lunfardo314/proxima/ledger/base"
	"github.com/lunfardo314/proxima/proxi/glb"
	"github.com/spf13/cobra"
)

// txidFieldWidth is the fixed column width for the transaction ID short string in log output
const txidFieldWidth = 30

func initTxLogCmd() *cobra.Command {
	txlogCmd := &cobra.Command{
		Use:   "txlog",
		Short: "transaction logger commands",
		Args:  cobra.NoArgs,
	}

	txlogCmd.AddCommand(
		initTxLogGetCmd(),
		initTxLogEnableCmd(),
		initTxLogDisableCmd(),
		initTxLogTailCmd(),
		initTxLogStatusCmd(),
	)

	return txlogCmd
}

func initTxLogGetCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <prefix>",
		Short: "list log messages for transactions matching the short ID prefix",
		Long:  "Retrieves log messages for transactions matching the given hex prefix of TransactionIDShort. Results are sorted ascending by log timestamp.",
		Args:  cobra.ExactArgs(1),
		Run:   runTxLogGetCmd,
	}

	cmd.Flags().IntP("max", "m", 100, "maximum number of records to return")

	return cmd
}

func runTxLogGetCmd(cmd *cobra.Command, args []string) {
	prefixHex := args[0]
	maxRecords, _ := cmd.Flags().GetInt("max")

	resp, err := glb.GetClient().TxLogGet(prefixHex, maxRecords)
	glb.AssertNoError(err)

	if len(resp.Records) == 0 {
		glb.Infof("no records found for prefix %s", prefixHex)
		return
	}

	// Sort records by timestamp ascending
	sortRecordsAscending(resp.Records)

	glb.Infof("found %d record(s) for prefix %s:", len(resp.Records), prefixHex)
	for _, rec := range resp.Records {
		// Timestamps are displayed in UTC
		ts := time.Unix(0, rec.ClockTimestamp).UTC()
		txid, err := base.TransactionIDFromHexString(rec.TxID)
		glb.AssertNoError(err)

		glb.Infof("  %s %-*s %s", ts.Format("2006-01-02 15:04:05.000"), txidFieldWidth, txid.StringShort(), rec.Message)
	}
}

func initTxLogEnableCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "enable",
		Short: "enable transaction logging",
		Long: `Enable transaction logging with the specified level.

Levels:
  off           - disable logging
  branch        - log branch transactions only
  sequencer     - log all sequencer transactions
  non_sequencer - log non-sequencer transactions only (default)
  all           - log all transactions`,
		Args: cobra.NoArgs,
		Run:  runTxLogEnableCmd,
	}

	cmd.Flags().StringP("level", "l", "non_sequencer", "log level: off, branch, sequencer, non_sequencer, all")

	return cmd
}

func runTxLogEnableCmd(cmd *cobra.Command, _ []string) {
	level, _ := cmd.Flags().GetString("level")

	resp, err := glb.GetClient().TxLogEnable(level)
	glb.AssertNoError(err)

	if resp.Enabled {
		glb.Infof("transaction logger enabled with level: %s", resp.Level)
	} else {
		glb.Infof("transaction logger disabled")
	}
}

func initTxLogDisableCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "disable",
		Short: "disable transaction logging",
		Args:  cobra.NoArgs,
		Run:   runTxLogDisableCmd,
	}

	return cmd
}

func runTxLogDisableCmd(_ *cobra.Command, _ []string) {
	resp, err := glb.GetClient().TxLogEnable("off")
	glb.AssertNoError(err)

	if !resp.Enabled {
		glb.Infof("transaction logger disabled")
	} else {
		glb.Infof("transaction logger is still enabled with level: %s", resp.Level)
	}
}

func initTxLogTailCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tail",
		Short: "list recent transaction log entries",
		Long:  "Retrieves log entries from the recent past. Default is last 1 minute.",
		Args:  cobra.NoArgs,
		Run:   runTxLogTailCmd,
	}

	cmd.Flags().IntP("back", "b", 1, "number of minutes to look back")
	cmd.Flags().IntP("max", "m", 100, "maximum number of records to return")

	return cmd
}

func runTxLogTailCmd(cmd *cobra.Command, _ []string) {
	backMinutes, _ := cmd.Flags().GetInt("back")
	maxRecords, _ := cmd.Flags().GetInt("max")

	if backMinutes <= 0 {
		backMinutes = 1
	}

	fromTime := time.Now().Add(-time.Duration(backMinutes) * time.Minute)
	fromNs := fromTime.UnixNano()

	resp, err := glb.GetClient().TxLogRange(fromNs, 0, maxRecords)
	glb.AssertNoError(err)

	if len(resp.Records) == 0 {
		glb.Infof("no records found in the last %d minute(s)", backMinutes)
		return
	}
	glb.SortAndPrintTxLog(resp.Records)
}

func initTxLogStatusCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "status",
		Short: "show transaction logger status",
		Args:  cobra.NoArgs,
		Run:   runTxLogStatusCmd,
	}
}

func runTxLogStatusCmd(_ *cobra.Command, _ []string) {
	resp, err := glb.GetClient().TxLogStatus()
	glb.AssertNoError(err)

	if resp.Enabled {
		glb.Infof("transaction logger: enabled, level: %s", resp.Level)
	} else {
		glb.Infof("transaction logger: disabled")
	}
}

// sortRecordsAscending sorts records by ClockTimestamp in ascending order
func sortRecordsAscending(records []api.TxLogRecord) {
	sort.Slice(records, func(i, j int) bool {
		return records[i].ClockTimestamp < records[j].ClockTimestamp
	})
}
